### ISSUE TITLE
Add a Contributing.md File

### ISSUE THREAD

**Issue by Tejas1510** [Tejas1510/Athavani#1]
The Contributing File Should consist of a Detailed explanation of how to contribute to the project with the use of images so beginners will find it easy to contribute

**Comment by kanishkaa24** [comment]
Hey!
I would love to work on this issue.

**Comment by Tejas1510** [comment]
Go Ahead @kanishkaa24

**Comment by kanishkaa24** [comment]
Kindly enlighten me with the required protocol.

**Comment by Tejas1510** [comment]
@kanishkaa24 you can refer this https://github.com/HarshCasper/Rotten-Scripts/blob/master/CONTRIBUTING.md 
We want to have a similar kind of file but the images used should be this current project
