### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by sanjay270899** [Tejas1510/Athavani#103]
- Update the contributors Table.
  - Remove tabular table and add image.  ([Refer this](https://remarkablemark.org/blog/2019/10/17/github-contributors-readme/))
- Update screenshots of website. As they are the screenshots of old version of website.
- Add `GSSOC` as Open Source Program.

**Comment by mitalirs** [comment]
Hello Sir, Could I try working on this as a participant for GSSoC'21?

**Comment by Tejas1510** [comment]
Go ahead @mitalirs

**Comment by PragatiBhat** [comment]
Can you assign me this task as GSSOC participant?

**Comment by sanjay270899** [comment]
@mitalirs Try this link: https://athavani-sanjay-frontend.netlify.app/

**Comment by mitalirs** [comment]
@sanjay270899  I tried using that, but when tried to sign up, after clicking on send OTP button it gave an 'invalid login' error message

**Comment by Tejas1510** [comment]
@mitalirs untill the problem solves you can use this dummy credentials
email: refce25@gmail.com
password : 1234567

**Comment by mitalirs** [comment]
Thank you @Tejas1510, will it be okay if I make changes and delete/create new memories for this profile?
Because I need to add the demonstrations(of creating/deleting/updating etc new memory) to the readme file

**Comment by Tejas1510** [comment]
Yes

**Comment by sanjay270899** [comment]
@mitalirs Update?

**Comment by mitalirs** [comment]
I have created the Pull Request. Please review it
