### ISSUE TITLE
New Layout

### ISSUE THREAD

**Issue by sanjay270899** [Tejas1510/Athavani#105]
We need to improve the layout of our website.

- This is the wireframe of present website
![image](https://user-images.githubusercontent.com/43892590/110472492-71db1400-8103-11eb-8b1b-4c8901c671cd.png)

- This is the new suggested wireframe from my side. (You can come with better wireframe if you have)
![image](https://user-images.githubusercontent.com/43892590/110472508-769fc800-8103-11eb-9557-6d9316338457.png)

- To solve this issue one should have decent knowledge of CSS, JSX, and Material UI.

**Comment by abhishek7997** [comment]
Please assign this issue to me. I will try my best to solve this issue.

**Comment by HarshitPandey251** [comment]
@sanjay270899 Please assing to me. As I have done in many webpage

**Comment by Tejas1510** [comment]
@HarshitPandey251 if we don't get PR from the assigned person with next 3 days we will assign the issue to you

**Comment by abhishek7997** [comment]
@sanjay270899 
How do I sign in or sign up? Both are not working. How do I access the memories page?

**Comment by mohammedjameel24** [comment]
assign it to me under gssoc

**Comment by sanjay270899** [comment]
@abhishek7997 Will solve this tonight.  Sorry for inconvenienced.

**Comment by abhishek7997** [comment]
@sanjay270899 I forked and checked the updated code, still doesn't work, browser console gives : 
Failed to load resource: the server responded with a status of 404 (Not Found)  https://memories-mern-stack.herokuapp.com/auth/signin

**Comment by mohammedjameel24** [comment]
I have seen this app on Javascript Mastery mern memories app 

I can resolve your issue 

Please assign me

**Comment by sanjay270899** [comment]
> @sanjay270899 I forked and checked the updated code, still doesn't work, browser console gives :
> Failed to load resource: the server responded with a status of 404 (Not Found) https://memories-mern-stack.herokuapp.com/auth/signin

Issue is solved now.
