### ISSUE TITLE
Header/Navbar of this project is pretty dull.

### ISSUE THREAD

**Issue by sayna3311** [Tejas1510/Athavani#108]
I am a GSSoC'21 participant and I would like to modify and improve the header/navbar including the icon because this looks quite familiar to a project on Youtube. Please assign this to me  : ).

**Comment by sanjay270899** [comment]
@sayna3311 Just for conformation, can you please send here an image of current Header of our website?

**Comment by Pranjal-2001** [comment]
Can I work on this issue?

**Comment by Oviyabalamurugan** [comment]
I am a GSSoC'21 participant.Header and footer for this website could improve a lot.With footer improvement like adding copyrights in the center and adding basic icons like facebook linkedin twitter whatsapp and instagram would be really attractive.In the darkmode option could be moved to the header itself it seems better in that way so not to confuse users.

**Comment by Priyanka7011** [comment]
I am a GSSOC 2021 participant.
I would love to work on this issue .Please assign me this.
Thank You

**Comment by sayna3311** [comment]
@sanjay270899 
![image](https://user-images.githubusercontent.com/67572440/110754117-71f72300-826d-11eb-81a5-fc1f8b791d80.png)
It's like this ig.
If approved,  I would like to work on this issue I created.

**Comment by Oviyabalamurugan** [comment]
![Athavani](https://user-images.githubusercontent.com/55582676/110757494-74f41280-8271-11eb-89e8-6f4988a4cb6f.png)
I would like to work upon the footer part of this page which we can use it as a footer for all the linked pages.

**Comment by sanjay270899** [comment]
@sayna3311 Any update?

**Comment by sanjay270899** [comment]
@Pranjal-2001 Go Ahead!
