### ISSUE TITLE
Cannot signup

### ISSUE THREAD

**Issue by AmeyaJain-25** [Tejas1510/Athavani#111]
I cannot signup or signin.
When I go for signup, it says user already exists although no email verification or nothing.
When I go for password reset, it says no email exists.

Please help me with this or if possible, provide dummy credentials to login.

**Comment by Tejas1510** [comment]
@AmeyaJain-25 There is some issue and @sanjay270899 is working on it and the issue will be resolved soon
Till then you can log in with these dummy credentials
email : refce25@gmail.com
password : 1234567

**Comment by AmeyaJain-25** [comment]
Thanks @Tejas1510

**Comment by abhishek7997** [comment]
@AmeyaJain-25 
Is the login working?
On my clone it is not working.

**Comment by Tejas1510** [comment]
@AmeyaJain-25 You have to add a .env file which will have a mongoose url 
You can create your mongoose URL by goging to mongoDB/Atlas
Just go through the .env.example file

**Comment by abhishek7997** [comment]
@Tejas1510 
I will try this, then get back to you.

**Comment by abhishek7997** [comment]
@Tejas1510 Sir, please give an example of a working .env file

**Comment by abhishek7997** [comment]
@Tejas1510 is this .env file correct?

PORT = "27017"
CONNECTION_URL = "mongodb://localhost:27017/athavani"
MAIL = "refce25@gmail.com"
PASS = "1234567"
JWT_KEY = "1234567"
RESET_PASSWORD_JWT_KEY = "1234567"
CLIENT_URL = "http://localhost:3000"

**Comment by AmeyaJain-25** [comment]
Same here.
I'm also not able to signup in local server. Getting issue of 'Invalid Login, Username and password not accepted

**Comment by sanjay270899** [comment]
@AmeyaJain-25 @abhishek7997 @sayna3311 @mitalirs

Hello Everyone! Sorry for inconvenience. I will update the code in some hours.

If you all want a short session for setting up our repo, then I will be happy to take it.
Do you all want a short session for setting this repo on your local machine?

**Comment by AmeyaJain-25** [comment]
> @AmeyaJain-25 @abhishek7997 @sayna3311 @mitalirs
> 
> Hello Everyone! Sorry for inconvenience. I will update the code in some hours.
> 
> If you all want a short session for setting up our repo, then I will be happy to take it.
> Do you all want a short session for setting this repo on your local machine?

Yes Sure, that will be really great

**Comment by abhishek7997** [comment]
> @AmeyaJain-25 @abhishek7997 @sayna3311 @mitalirs
> 
> Hello Everyone! Sorry for inconvenience. I will update the code in some hours.
> 
> If you all want a short session for setting up our repo, then I will be happy to take it.
> Do you all want a short session for setting this repo on your local machine?

Yes

**Comment by mitalirs** [comment]
> @AmeyaJain-25 @abhishek7997 @sayna3311 @mitalirs
> 
> Hello Everyone! Sorry for inconvenience. I will update the code in some hours.
> 
> If you all want a short session for setting up our repo, then I will be happy to take it.
> Do you all want a short session for setting this repo on your local machine?

Yes

**Comment by sanjay270899** [comment]
@AmeyaJain-25 @abhishek7997 @mitalirs Great!

Have to joined `GSSOC(GS)'s Server` ?

I will post a google meet link there. We will keep meet around 5-6 PM.

![image](https://user-images.githubusercontent.com/43892590/110859179-0f3f6f00-82e1-11eb-80a4-c8fc4f7949a0.png)

**Comment by abhishek7997** [comment]
The project channels are not visible.

**Comment by AmeyaJain-25** [comment]
Project channels aren't visible to the participants. They will be available for us within some days.

**Comment by sanjay270899** [comment]
@AmeyaJain-25 @abhishek7997 @mitalirs

Now you can access the `Athavani` channel in GSSOC server. I have posted a google meet link their. We will meet at 5:00 PM 13th March'21.

**Comment by sanjay270899** [comment]
@AmeyaJain-25 Closing this issue. Signup issue is solved.
