### ISSUE TITLE
Add GSSoC in the Readme

### ISSUE THREAD

**Issue by itsIapetus** [Tejas1510/Athavani#112]
**Is your feature request related to a problem? Please describe.**
I noticed only Devscript Winter of code is in the readme, I would like to add GSSoC logo too.

**Describe the solution you'd like**
Addition of GSSoC logo in the readme under Open Source

**Describe alternatives you've considered**

**Additional context**

**Comment by itsIapetus** [comment]
Could you assign it to me under gssoc'21, thank you.

**Comment by sanjay270899** [comment]
@itsIapetus Issue already exist. Issue #103

**Comment by itsIapetus** [comment]
Okayy, sorry didn't see.
