### ISSUE TITLE
Design of Sign In/Sign up form can be improved

### ISSUE THREAD

**Issue by Priyanka7011** [Tejas1510/Athavani#113]
hey!
I am a GSSOC 2021 participant.
I can improve the design of the sign in/sign up form . I can make it look better by using proper layout and gradient for the form. It will surely enhance the look of the website.
Also on smaller screen devices there's no margin from right .I can fix this issue and make it responsive for smaller screen devices.

Please assign me this issue. I would love to work on it. I will give my best.

Thank You

**Comment by sanjay270899** [comment]
@Priyanka7011 Go Ahead!

**Comment by Priyanka7011** [comment]
Okay sir !
Thank You

**Comment by Priyanka7011** [comment]
I have raised a PR .Please review it .
