### ISSUE TITLE
Enhancement of the footer

### ISSUE THREAD

**Issue by Oviyabalamurugan** [Tejas1510/Athavani#114]
In an usual footer there must be essential details to connect to the website holder example icons of facebook,linkedin,twitter,github and many more,so that they get the connectivity and know about the website more.I would like to enhance the website by adding a better footer.I am a participant of GSSOC21.

**Comment by sanjay270899** [comment]
@Oviyabalamurugan Go Ahead!

**Comment by sanjay270899** [comment]
@Oviyabalamurugan Any update?

**Comment by Oviyabalamurugan** [comment]
working on it will provide it by today.

**Comment by Oviyabalamurugan** [comment]
![image](https://user-images.githubusercontent.com/55582676/111714401-922f6f00-8877-11eb-9de5-1d05d42db4e6.png)
This is the current state of the footer i have to change stylings of the footer and legal__links class that have been provided.Can i proceed over it.

**Comment by Ankita297** [comment]
Can i work on this ?

**Comment by prerna2712** [comment]
Can I work on this?

**Comment by sanjay270899** [comment]
@Ankita297 Go Ahead!

**Comment by Ankita297** [comment]
@sanjay270899  i am working on it . I will make the PR soon .

**Comment by Ankita297** [comment]
![Athavani - Google Chrome 30-03-2021 16_58_52 (1)](https://user-images.githubusercontent.com/67833077/112981784-48009480-9179-11eb-91e2-dbc8e3e2d9f0.png)

**Comment by Ankita297** [comment]
@sanjay270899 is it okay ?
Or any other changes ?

**Comment by sanjay270899** [comment]
@Ankita297 Increase the top margin. And try to decrease the height of it. Rest is fine.
