### ISSUE TITLE
On Refreshing the page, throwing netlify error

### ISSUE THREAD

**Issue by ShubhamSj07** [Tejas1510/Athavani#116]
**Describe the bug**
On refreshing the page, it gives an error of page not found(404) from netlify.

**To Reproduce**
1. Go to 'https://memoriestejastapas.netlify.app/signin'
2. Click on 'Reload Button' to refresh page
3. See error

**Expected behavior**
On refreshing or reloading the page , it should  render the page as it is
There's an error for redirection and routing when we use netlify.

I can help with this issue 
Please assign me this issue 

Thanks

**Comment by Tejas1510** [comment]
Go ahead

**Comment by ShubhamSj07** [comment]
> Hello there!👋 Welcome to the project!🚀⚡
> Thank you and congrats🎉 for opening your very first issue in this project. Athavani is a full-stack MERN Tool built in order to save all your memories in a single place and rejoice them through the years. Please adhere to our [Code of Conduct](https://github.com/Tejas1510/Athavani/blob/master/CODE_OF_CONDUCT.md). Please make sure not to start working on the issue, unless you get assigned to it.😄

**Comment by ShubhamSj07** [comment]
@Tejas1510 , I am new to open-source contribution , i am not a gssoc 2021 participant.
Sorry for that, can i get to resolve this issue?

**Comment by Tejas1510** [comment]
Go ahead @ShubhamSj07
