### ISSUE TITLE
Add dark mode 

### ISSUE THREAD

**Issue by itsIapetus** [Tejas1510/Athavani#118]
**Is your feature request related to a problem? Please describe.**
I would like to add dark mode if it's not already present.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Tejas1510** [comment]
Go ahead @itsIapetus

**Comment by abhishek7997** [comment]
Is the project working on your system? @itsIapetus

**Comment by kanishkaa24** [comment]
Hello! Can I work on this under GSSOC ?

**Comment by jaiswalrobin** [comment]
@sanjay270899  can you please assign this issue to me under GSSOC.
Thankyou
