### ISSUE TITLE
Add a heart icon in the Card

### ISSUE THREAD

**Issue by Tejas1510** [Tejas1510/Athavani#12]
Add a Heart Icon in the Card which turns red on clicking and is added to favorite Category
We will be having various option to filter card 
It will also be an option

**Comment by sakshikhachane** [comment]
Hi @Tejas1510 ,
I would like to work on this issue. I am good at backend as well as frontend. Please assign me this issue.

**Comment by Tejas1510** [comment]
Go ahead @sakshikhachane

**Comment by luckykumarirai** [comment]
Hello @Tejas1510 
I would like to work on this issue because  I have implemented the same thing in my project (heart icon present on the card if u click on the heart for adding the favorite then its turn into red).

**Comment by sanjay270899** [comment]
I would Like to work on this if @sakshikhachane is facing any difficulty.

**Comment by sanjay270899** [comment]
@Tejas1510 If you allow me then, should I start working on this?

**Comment by Tejas1510** [comment]
Go ahead @sanjay270899 
Also you have to add a sorting feature where a category will be present of favorite so all card with favorite will be shown

**Comment by sanjay270899** [comment]
Sure.

**Comment by sanjay270899** [comment]
Where should I keep the heart icon?

**Comment by Tejas1510** [comment]
to the right of like button

**Comment by sanjay270899** [comment]
@Tejas1510 Before this, I will need the Authentication part. Should I implement that issue(#6 ) also?

**Comment by kenkirito** [comment]
@Tejas1510 assign me this

**Comment by Tejas1510** [comment]
@kenkirito go ahead

**Comment by kenkirito** [comment]
Thanks @Tejas1510 I will try to submit pr in the morning

**Comment by kenkirito** [comment]
@Tejas1510 i am also done with the issue should I also make a pr
