### ISSUE TITLE
New UI and design for the Create Post Card

### ISSUE THREAD

**Issue by AmeyaJain-25** [Tejas1510/Athavani#123]
**Is your feature request related to a problem? Please describe.**
The UI is dull and not good. Also the creator name is in input bar with disabled. The choose file button is also not good.

**Describe the solution you'd like**
I will be changing the UI a bit and add the customized button for uploading the file. Also the validation would be improved

**Additional context**
Please assign me this issue under GSSoC 21'

**Comment by sanjay270899** [comment]
@AmeyaJain-25 Go Ahead!

**Comment by sanjay270899** [comment]
@AmeyaJain-25 Any update?

**Comment by AmeyaJain-25** [comment]
Yes, I've done the CSS part.
Validation is remaining. Will be making PR by tomorrow evening

**Comment by kanishkaa24** [comment]
Hello! Can I work on this under GSSOC ?
