### ISSUE TITLE
Disable creator field

### ISSUE THREAD

**Issue by ashishnagpal2498** [Tejas1510/Athavani#124]
**Describe the bug**
Creator field should be disabled as creator will be the profile owner only.

**To Reproduce**
1. Login with credentials
2. Check for right form

**Expected behavior**
The creator field should be disabled, hence -
1. Change cursor pointer
2. Change background color

**Screenshots**
![Inkedathavani_issue1_1](https://user-images.githubusercontent.com/36301481/111066607-e2a87480-84e5-11eb-85ec-c19d920f3c32.jpg)

**Comment by ShubhamSj07** [comment]
@ashishnagpal2498 , would u pls provide dummy  credentials for login

**Comment by sanjay270899** [comment]
@ashishnagpal2498 Creator field is already disabled.

**Comment by ashishnagpal2498** [comment]
@sanjay270899 . The field is disabled. But it doesn't look like. That's what I meant. Changing cursor to blocked and color of the field - grey maybe.

**Comment by ashishnagpal2498** [comment]
@ShubhamSj07 assigning it to you. 1 issue at a time.

**Comment by sanjay270899** [comment]
Solved in PR #134
