### ISSUE TITLE
Change Buttons

### ISSUE THREAD

**Issue by ashishnagpal2498** [Tejas1510/Athavani#126]
**Is your feature request related to a problem? Please describe.**
Change submit and clear buttons to icons. 

**Describe the solution you'd like**
Use better color coding and icons for the existing buttons. Svg or use font-awesome 

![Inkedathavani_issue1_3](https://user-images.githubusercontent.com/36301481/111066961-c9082c80-84e7-11eb-9a2d-9f6b11b18160.jpg)

**Comment by Cgoyal48** [comment]
Hey @Tejas1510,
what exactly do you mean by change buttons?
will you please explain in detail so that I can contribute to this issue.
I am a GSSOC'21 participant .

**Comment by Tejas1510** [comment]
@ashishnagpal2498 can you please describe in detail as @Cgoyal48 will get a better understanding

**Comment by ashishnagpal2498** [comment]
So, basically you have to make buttons more appealing. In single line. Prefer flex boxes for it. 
Reference - 
![image](https://user-images.githubusercontent.com/36301481/111073326-49d52180-8504-11eb-9263-54d8b2cf0d85.png)

**Comment by rajesh6161** [comment]
@ashishnagpal2498  I want to work on this issue. It will be better to use flex box. Please assign this issue to me.

**Comment by Cgoyal48** [comment]
> So, basically you have to make buttons more appealing. In single line. Prefer flex boxes for it.
> Reference -
> ![image](https://user-images.githubusercontent.com/36301481/111073326-49d52180-8504-11eb-9263-54d8b2cf0d85.png)

@ashishnagpal2498 Thank you. I got it . I can surely handle the issue. Can you please assign the issue to me, I will start working on it immediately .

**Comment by Tejas1510** [comment]
go ahead @Cgoyal48

**Comment by Cgoyal48** [comment]
> go ahead @Cgoyal48

Thank you sir for assigning the issue to me.

**Comment by Cgoyal48** [comment]
Hey @Tejas1510 just wanted to ask how I can see my changes as my backend is not working?

**Comment by sanjay270899** [comment]
@Cgoyal48 Backend is working. You have to add your own keys in `.env` file in `server` folder (refer `.env.example` file). Also, change the URL to localhost in `index` file of `API` folder in `client`.

**Comment by Cgoyal48** [comment]
> @Cgoyal48 Backend is working. You have to add your own keys in `.env` file in `server` folder (refer `.env.example` file). Also, change the URL to localhost in `index` file of `API` folder in `client`.

@sanjay270899 okay. Thank you!

**Comment by Bishal05** [comment]
@Tejas1510 is the issue still open? If yes then can you assign me this project . I am a participant in gssoc 21

**Comment by soumalyatheking22012001** [comment]
@Tejas1510,   @Cgoyal48 @Bishal05 are in the line but still I would also like to give a try can I do it ?

**Comment by Tejas1510** [comment]
@sanjay270899 Please have a look at it

**Comment by soumalyatheking22012001** [comment]
@Tejas1510 thank you

**Comment by sanjay270899** [comment]
@Cgoyal48 any update?

**Comment by Cgoyal48** [comment]
> @Cgoyal48 any update?

Sir today we talked on discord and you said you will be taking an meeting tomorrow on which we will be discussing the problemi asked you other than that I have created the component to be used, So it's like just I have to use that component after that meeting.

**Comment by kanishkaa24** [comment]
Hello! Can I work on this under GSSOC ?

**Comment by sanjay270899** [comment]
Hello Everyone @Cgoyal48 @rajesh6161 @Bishal05 @soumalyatheking22012001 @kanishkaa24 
Today I will take a short google meet for setting up this Repo on your local machine. Meet will be at 4:00 PM IST Today. I wil provide meet link on GSSoC'21 Discord Server in Athavani Channel. So, if anyone is interested then they can join.

**Comment by soumalyatheking22012001** [comment]
@sanjay270899 can you give me the link to the server I cannot find it in discord

**Comment by sanjay270899** [comment]
> @sanjay270899 can you give me the link to the server I cannot find it in discord. The link in `Readme.md` is expired

https://meet.google.com/wmp-qewm-bfo

**Comment by soumalyatheking22012001** [comment]
> > @sanjay270899 can you give me the link to the server I cannot find it in discord. The link in `Readme.md` is expired
> 
> https://meet.google.com/wmp-qewm-bfo

Is meeting over ?
