### ISSUE TITLE
Loading state position

### ISSUE THREAD

**Issue by ashishnagpal2498** [Tejas1510/Athavani#127]
**To Reproduce**
1. Log into project
2. Click on 'My profile'
3. See error

**Expected behavior**
It should be centered and with visible color.

**Screenshots**
![Inkedathavani_issue2_](https://user-images.githubusercontent.com/36301481/111067163-eab5e380-84e8-11eb-97da-bbe783fb1281.jpg)

**Comment by Supriya1702** [comment]
I am a GSSOC'21 aspirant. I would like to work on this, Please assign this to me.

**Comment by Tejas1510** [comment]
Go ahead @Supriya1702

**Comment by Supriya1702** [comment]
@Tejas1510 Could I get dummy credentials?

**Comment by sanjay270899** [comment]
@Supriya1702 
https://athavani-sanjay-frontend.netlify.app/
