### ISSUE TITLE
Suggest Improvement

### ISSUE THREAD

**Issue by Tejas1510** [Tejas1510/Athavani#13]
If you Think any issue would help to improve the project you can suggest that and we would think on it

**Comment by antaramunshi** [comment]
i think we should add an issue regarding the like button since a user can add multiple likes and it shouldn't be so

**Comment by Tejas1510** [comment]
@antaramunshi Good observation 
Currently we are adding a feature of authentication and then we will take issue into account 
I will then assign it to you

**Comment by luckykumarirai** [comment]
Hello @Tejas1510 
Run Backend and Frontend(React) with a single command for this little change need in the structure of the project.
it would help users.

**Comment by luckykumarirai** [comment]
Add issue templates that help the developer to easily find the file or folder where implement their own idea and make fantastic.
According to issue templates, some steps needs to follow during the rise issue by the developer.

**Comment by Tejas1510** [comment]
> Add issue templates that help the developer to easily find the file or folder where implement their own idea and make fantastic.
> According to issue templates, some steps needs to follow during the rise issue by the developer.

Go ahead @luckykumarirai

**Comment by Tejas1510** [comment]
> Hello @Tejas1510
> Run Backend and Frontend(React) with a single command for this little change need in the structure of the project.
> it would help users.

Currently we are looking to have both frontend and backend separate so e don;t need this at this point of time
If required I Will surely assign you

**Comment by luckykumarirai** [comment]
> > Add issue templates that help the developer to easily find the file or folder where implement their own idea and make fantastic.
> > According to issue templates, some steps needs to follow during the rise issue by the developer.
> 
> Go ahead @luckykumarirai

hello @Tejas1510 
you have already an issue template.

**Comment by Tejas1510** [comment]
@luckykumarirai I thought which help user understand the folder structure 
No worries I will close this issue

**Comment by vedikaag99** [comment]
@Tejas1510 I think the website requires a proper logo as well that can also be used as favicon. I can design it if you want.

**Comment by Tejas1510** [comment]
@vedikaag99 Thanks for the issue 
We already have many logos created so we don't one
