### ISSUE TITLE
DARK MODE UI

### ISSUE THREAD

**Issue by mohammedjameel24** [Tejas1510/Athavani#131]
## Dark Mode UI

Adding a widget to toggle dark mode and light mode theme in webpage

**Comment by soumalyatheking22012001** [comment]
Can you please elaborate what do you want @mohammedjameel24 
It would be better to understand your demand correctly and then work on it

**Comment by mohammedjameel24** [comment]
> Can you please elaborate what do you want @mohammedjameel24 
> It would be better to understand your demand correctly and then work on it

Issue edited

**Comment by soumalyatheking22012001** [comment]
ok thank you can I work on it @Tejas1510

**Comment by Tejas1510** [comment]
Go ahead @soumalyatheking22012001

**Comment by mohammedjameel24** [comment]
I created the issue i should get assigned

**Comment by mohammedjameel24** [comment]
> Can you please elaborate what do you want @mohammedjameel24 
> It would be better to understand your demand correctly and then work on it

PLEASE ASSIGN ME !

**Comment by kanishkaa24** [comment]
Hello! Can I work on this under GSSOC ?

**Comment by mohammedjameel24** [comment]
pull request #138

**Comment by soumalyatheking22012001** [comment]
Ok I would go ahead now
