### ISSUE TITLE
Not able to sign up. Missing credentials for 'PLAIN'

### ISSUE THREAD

**Issue by AmrutaKoshe** [Tejas1510/Athavani#133]
**Describe the bug**
When I try to sign up/ create an account, it asks for my email id. After providing it and clicking on "send OTP" button, it displays a pop-up saying "Missing credentials for PLAIN". The email id is valid and I tried with different email ids, but this issue still persists.

**To Reproduce**
1. Go to 'https://memoriestejastapas.netlify.app/signup'
2. Fill your email id
3. Click on "SEND OTP"

![image](https://user-images.githubusercontent.com/59871941/111453003-1cbd8480-8739-11eb-8720-ca6d40e1bdf3.png)

**Expected behavior**
The user should receive an OTP in their mail

**Comment by Tejas1510** [comment]
@AmrutaKoshe use this link
It will solve the issue 
https://athavani-sanjay-frontend.netlify.app/

**Comment by AmrutaKoshe** [comment]
> @AmrutaKoshe use this link
> It will solve the issue
> https://athavani-sanjay-frontend.netlify.app/

okay! so the website link of the repo has to be updated 😅

**Comment by soumalyatheking22012001** [comment]
Is this issue fixed ?

**Comment by sanjay270899** [comment]
Yes.
