### ISSUE TITLE
Discord Sever invite link in Readme file is Expired

### ISSUE THREAD

**Issue by soumalyatheking22012001** [Tejas1510/Athavani#137]
**Describe the bug**
Discord Server link in `Readme.md` is expired.
**To Reproduce**
1. Click the discord server link in the top of `Readme.md`
**Expected behavior**
After clicking the link should take me to the desired Server giving me an option to join it.

**Screenshots**
![image](https://user-images.githubusercontent.com/59192460/111758811-ec095680-88c2-11eb-99cb-b7d6688c9879.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Microsoft Edge
 - Version: 89

**Comment by sanjay270899** [comment]
@Tejas1510 Should we create our own Athavani Discord Server?

**Comment by Tejas1510** [comment]
@sanjay270899 ya sure we can create our own server

**Comment by soumalyatheking22012001** [comment]
@sanjay270899 @Tejas1510 Then after creating the server please update it in the readme file

**Comment by sanjay270899** [comment]
@soumalyatheking22012001 Updated the Discord Link in README.md.

**Comment by soumalyatheking22012001** [comment]
@sanjay270899 @Tejas1510 Thank you

**Comment by soumalyatheking22012001** [comment]
I'm closing the issue
