### ISSUE TITLE
Improve The Layout Of Modal

### ISSUE THREAD

**Issue by Tejas1510** [Tejas1510/Athavani#14]
The Current Modal is as follows
![image](https://user-images.githubusercontent.com/64543913/103165131-e65b2200-4839-11eb-8a96-fcf29a092dd0.png)

You have to change the layout of Modal So as to Make it Look nice and Professional

**Comment by SuNiL-Chau** [comment]
Hey @Tejas1510 can I give it a shot?

**Comment by Tejas1510** [comment]
Go for it @SuNiL-Chau

**Comment by Aniket31-coder** [comment]
Hey!
I would like to contribute to this issue! Is the modal only for the admin password and submit button?

**Comment by Tejas1510** [comment]
@Aniket31-coder Go ahead
Main attention will be given to the design

**Comment by Tejas1510** [comment]
@Aniket31-coder till then of you any new modifications you may create a new issue and I will look into it

**Comment by Aniket31-coder** [comment]
Okay, sure!

**Comment by SuNiL-Chau** [comment]
Hey @Tejas1510  kindly have a look the below design and provide your feedback on it
https://www.figma.com/file/CeSMTqLpk9idj2kVc4HrVB/aathavni-modal?node-id=0%3A1

**Comment by Tejas1510** [comment]
@SuNiL-Chau It is showing file not exist

**Comment by Tejas1510** [comment]
Add a screenshot here

**Comment by SuNiL-Chau** [comment]
@Tejas1510 Here is the picture
![Frame 1](https://user-images.githubusercontent.com/46418190/103211010-1afbd600-492d-11eb-9559-a88d93ca313e.png)

**Comment by Tejas1510** [comment]
The design looks good
Just center the button
And use a different color option

**Comment by SuNiL-Chau** [comment]
Okay sure

**Comment by SuNiL-Chau** [comment]
Hey @Tejas1510  have a look
![Frame 1](https://user-images.githubusercontent.com/46418190/103214957-f0634a80-4937-11eb-81d4-95569e88fa26.png)

**Comment by Tejas1510** [comment]
@SuNiL-Chau this is  awesome 
Just one thing if this is responsive 
You are good to create a Pr
I will merge it

**Comment by SuNiL-Chau** [comment]
Okay @Tejas1510 will do the code tom & check it then will send or as it is done :+1:

**Comment by SuNiL-Chau** [comment]
Hey, @Tejas1510  have a look at the changes & the file was actually mistakenly beautified.

**Comment by SuNiL-Chau** [comment]
Hey, @Tejas1510 I hope this issue is closed if it's closed then kindly assign this issue to me and close it thanks :)
