### ISSUE TITLE
Auth pages not responsive for mobile devices.

### ISSUE THREAD

**Issue by jaiswalrobin** [Tejas1510/Athavani#141]
### Is your feature request related to a problem? Please describe.
 Currently the login form in the homepage is not responsive.

### Describe the solution you'd like.
I would like to make the login form responsive by correcting the width of the container and  set the input width so that it is responsive on all devices and hence a better user experience. I am gssoc21 participant and I would like to solve the issue so please assign it to me. Thankyou.

**Comment by sanjay270899** [comment]
@jaiswalrobin Go Ahead!

**Comment by jaiswalrobin** [comment]
@sanjay270899  I have made sign up and sign in form responsive. Do you want me to make changes in other pages also because there is no structure in the profile pages when display size is reduced?

**Comment by jaiswalrobin** [comment]
@sanjay270899  for reference this is the screenshot :
<img width="505" alt="defect" src="https://user-images.githubusercontent.com/72142375/112608733-af98a600-8e40-11eb-8d19-eb4f988b756b.PNG">

Thankyou.

**Comment by jaiswalrobin** [comment]
@sanjay270899 I have made a pull request regarding responsiveness of sign-in, sign-up, and forgot password page. please check.
