### ISSUE TITLE
Unable to sigup 

### ISSUE THREAD

**Issue by hridhi** [Tejas1510/Athavani#147]
**Describe the bug**
When i tried to click the signup after typing out my email it didnt sigup and showed invalid error  

**Expected behavior**
It should send an otp

**Screenshots**
![image](https://user-images.githubusercontent.com/57177761/112132287-6fdb7f80-8bf0-11eb-958d-dee403c9c908.png)

**Desktop (please complete the following information):**
 - OS:windows
 

**Additional context**
please add the tag GSSoc

**Comment by sanjay270899** [comment]
@hridhi Thanks for letting us know about this error. Also, your screenshot helps us to solve this issue quickly. `Google Refresh Token` got expired. Now I have regenerated it. Thanks Again.
