### ISSUE TITLE
Join Athavani's Discord Server.

### ISSUE THREAD

**Issue by sanjay270899** [Tejas1510/Athavani#148]
https://discord.com/invite/gEqSYzc5Yu

**Comment by ShubhamSj07** [comment]
@sanjay270899 , not able to set-up backend locally, pls help me out!
can we have a meet for setting backend ?

**Comment by sanjay270899** [comment]
> @sanjay270899 , not able to set-up backend locally, pls help me out!
> can we have a meet for setting backend ?

Sure.
