### ISSUE TITLE
Integrating Google Sign-In

### ISSUE THREAD

**Issue by AasthaCodex** [Tejas1510/Athavani#149]
i would like to add Integrating Google Sign-In to login into the website. Please assign me this. 
A clear and concise description of what the problem is.
Normally, users prefer logging in with Google or Facebook to avoid filling up forms.

**Comment by sanjay270899** [comment]
@AasthaCodex Go Ahead!

**Comment by sanjay270899** [comment]
@AasthaCodex Any update?

**Comment by AasthaCodex** [comment]
Finished half of it, will be done soon.

**Comment by AasthaCodex** [comment]
@sanjay270899 Hey can you give me your mail? I want to ask you few things.

**Comment by sanjay270899** [comment]
@AasthaCodex https://discord.com/invite/gEqSYzc5Yu

**Comment by Ankita297** [comment]
@sanjay270899  can i work on this ?

**Comment by sanjay270899** [comment]
@Ankita297 Go Ahead!

**Comment by Ankita297** [comment]
@sanjay270899  can we use firebase ?

**Comment by sanjay270899** [comment]
@Ankita297 Okay

**Comment by sanjay270899** [comment]
@Ankita297 Any update?

**Comment by Ankita297** [comment]
@sanjay270899  sorry for late reply . I am busy on some of college work .  I will try  my best to resolve this .

**Comment by sanjay270899** [comment]
@AmeyaJain-25 @EkjotKaur want to try this one?

**Comment by AmeyaJain-25** [comment]
@sanjay270899 Currently I'm having my university exams.
I will be resuming my work from 9th of April.
But I'm sure that I can do this.

So, if it's late then I have no issues if @EkjotKaur wants to go ahead.

Or else I'll start from 9th if you have no issues with it.

**Comment by theBeginner86** [comment]
I want to work on this issue. As GSSOC'21 participant.

**Comment by sanjay270899** [comment]
@theBeginner86 Go Ahead!

**Comment by theBeginner86** [comment]
@sanjay270899 could you please help me in setting up the project on local machine. I have tried to follow the README but was not able to do it.
The following is the error I am facing:
<img width="872" alt="Screenshot 2021-05-05 at 5 19 09 PM" src="https://user-images.githubusercontent.com/73700530/117136909-9df2d880-adc6-11eb-874b-0ae29c9a31cd.png">

**Comment by sanjay270899** [comment]
@theBeginner86 

> @sanjay270899 could you please help me in setting up the project on local machine. I have tried to follow the README but was not able to do it.
> The following is the error I am facing:
> <img alt="Screenshot 2021-05-05 at 5 19 09 PM" width="872" src="https://user-images.githubusercontent.com/73700530/117136909-9df2d880-adc6-11eb-874b-0ae29c9a31cd.png">
> 
> I feel that it is not able to connect to MongoDB.

I have sent a message on discord to you.

**Comment by theBeginner86** [comment]
@sanjay270899 
Update:
I am still working on it. I am able to console log user's gmail details after he/she clicks on signing with google. I just have to figure out a way to use it to get to the home page and make other things work as usual. 
Will try to make the PR soon.

For now signing page looks as follows:
<img width="1440" alt="Screenshot 2021-05-07 at 11 31 03 PM" src="https://user-images.githubusercontent.com/73700530/117490540-86654c80-af8c-11eb-8ddd-601f6ff22341.png">
