### ISSUE TITLE
No need to use body-parser when using express version 4.16+

### ISSUE THREAD

**Issue by abhay27chauhan** [Tejas1510/Athavani#151]
## Is your feature request related to a problem? Please describe.
Express version 4.16+, their own body-parser implementation is now included in the default Express package so there is no need for you to download another dependency.

## Describe the solution you'd like
You have added a line to your code that looks like the following:

- app.use(bodyparser.json({ limit: '30mb', extended: true })); 

If you are using Express 4.16+ you can now replace that line with:

- **app.use(express.json({ limit: '30mb', extended: true }));** 

you also have the following code in your environment:

- app.use(bodyParser.urlencoded({ limit: '30mb', extended: true }));

You can replace that with:

- **app.use(express.urlencoded({ limit: '30mb', extended: true }));**

**Comment by abhay27chauhan** [comment]
I am a participant of GSSOC21, so please let me know if this is a valid proposal

**Comment by sanjay270899** [comment]
@abhay27chauhan Great! Go Ahead!
