### ISSUE TITLE
Error after initial connection was established, not handled

### ISSUE THREAD

**Issue by abhay27chauhan** [Tejas1510/Athavani#153]
**Is your feature request related to a problem? Please describe.**

snippet of you code -

```
mongoose.connect(process.env.CONNECTION_URL, { useNewUrlParser: true, useUnifiedTopology: true })
    .then(() => app.listen(PORT, () => console.log(`Server is running on Port ${PORT}`)))
    .catch((error) => console.log(error.message))
```

read this pls, the error handling part -
https://mongoosejs.com/docs/connections.html#:~:text=If%20initial%20connection%20fails%2C%20Mongoose,after%20initial%20connection%20was%20established.

you have handle two errors -

if promise is rejected -> using the above code i have proposed
error after initial connection is made -> using the event handlers

**Describe the solution you'd like**
To handle errors after initial connection was established, you should listen for error events on the connection.

**Comment by abhay27chauhan** [comment]
I am a participant of GSSOC21, so please let me know if this is a valid proposal

**Comment by sanjay270899** [comment]
@abhay27chauhan Go Ahead!
