### ISSUE TITLE
Bug in GitHub AutoAssign Mentors 

### ISSUE THREAD

**Issue by muthuannamalai12** [Tejas1510/Athavani#156]
When Running the GitHub action to auto-assign Mentors for every PR it displays a [warning]Resource not accessible by integration` when running against PRs and it does not auto-assign reviewers. Similar to the issue link given below 👇
kentaro-m/auto-assign-action#29

**Comment by muthuannamalai12** [comment]
I would love to work on this issue as a part of Girl Script Summer of Code. Kindly assign it to me.

**Comment by sanjay270899** [comment]
@Tejas1510 Do we need this feature?

**Comment by Tejas1510** [comment]
@sanjay270899 there is not a very immediate need but if you think it will add something valuable to the project you can assign it

**Comment by sanjay270899** [comment]
@muthuannamalai12 Go Ahead!
