### ISSUE TITLE
To add - Show Password - feature in Sign Up form

### ISSUE THREAD

**Issue by pratyushchamola** [Tejas1510/Athavani#158]
**Is your feature request related to a problem? Please describe.**
While setting the password in the **Sign Up** form , user won't be able to see it, as the option is not been provided

**Describe the solution you'd like**
Adding a logic to make the password visible to user when he desires.
i.e,

From this:
![athavani-from](https://user-images.githubusercontent.com/69751991/112674272-b8fb3000-8e8b-11eb-975b-4e30c38a1267.png)

To this:
![athavani-to](https://user-images.githubusercontent.com/69751991/112674298-c0bad480-8e8b-11eb-9799-7e769a728b9b.png)

**Additional context**
I am a participant of GSSOC21, and would like to solve the issue, so please assign it to me.
Thank You

**Comment by sanjay270899** [comment]
@pratyushchamola Just wanted to know that is this feature require?

**Comment by pratyushchamola** [comment]
@sanjay270899,  I felt, as a user, when you setup an alphanumeric password for the very first time, it's always helpful if you can preview and crosscheck it, before confirming. Thus, I think this feature would be beneficial if provided.

**Comment by sanjay270899** [comment]
@pratyushchamola Right, that's why, for confirming we have 2 password input boxes. But as this is your first issue, Go Ahead!

**Comment by pratyushchamola** [comment]
Thank you,  @sanjay270899

**Comment by DineshKoushik** [comment]
@pratyushchamola, I'm working on this.
