### ISSUE TITLE
Adding a homepage like feature with navbar

### ISSUE THREAD

**Issue by ShambhaviSharma0110** [Tejas1510/Athavani#165]
**Is your feature request related to a problem? Please describe.**
A homepage like feature with navbar and footer and other pages guides the user better

**Describe the solution you'd like**
a homepage with a navbar having elements like aboutus, contact,etc  and footer with contact and social handle info
**Describe alternatives you've considered**
none
**Additional context**
none

**Comment by sanjay270899** [comment]
@ShambhaviSharma0110 Go Ahead!

**Comment by ShambhaviSharma0110** [comment]
cool! I'll start working on it then
