### ISSUE TITLE
Error Message not disappearing. 

### ISSUE THREAD

**Issue by EkjotKaur** [Tejas1510/Athavani#175]
![IssueErrorMessage](https://user-images.githubusercontent.com/66993173/113729572-c24e8d00-9714-11eb-8bd8-a1c668092cb6.png)

When I filled the values incorrectly then an error message occurs, so I type the correct values now. The error message still occurs.
I summited it error message still occurs

@Tejas1510 @sanjay270899 assign me this issue

**Comment by sanjay270899** [comment]
@EkjotKaur Go Ahead!
