### ISSUE TITLE
Problem with upload your memory in Creating a memory form.

### ISSUE THREAD

**Issue by ayushjha952** [Tejas1510/Athavani#176]
**Describe the bug**
Upon clicking upload the file doesn't prompt anything. Instead we have to click below it.
and and also submit and clear button are overlapping.

**To Reproduce**
1. Go to Creating a Memory form after log in.
2. Click on Upload Your Memory.
3. See error

**Expected behavior**
Upon clicking Upload Your Memory a screen should pop up to upload memory.

**Screenshots**
![image](https://user-images.githubusercontent.com/60105854/113730476-8ff15f80-9715-11eb-8d23-e5da29c0b020.png)

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [chrome]
 - Version [89]

**Comment by ayushjha952** [comment]
Can you assign this issue to me?

**Comment by sanjay270899** [comment]
@ayushjha952 Go Ahead!
But remember. It is not working when it is hosted. When running on local machine it is working fine.
![image](https://user-images.githubusercontent.com/43892590/113773177-4ae42200-9743-11eb-8046-3a1efa4bbb37.png)

**Comment by ayushjha952** [comment]
@sanjay270899 I am not able to start the project the project?

**Comment by ayushjha952** [comment]
And your form is different from my from how ?

**Comment by sanjay270899** [comment]
@ayushjha952 https://discord.com/invite/gEqSYzc5Yu
