### ISSUE TITLE
Major Bug: User cannot delete their own comment on someone else's post

### ISSUE THREAD

**Issue by N-Shar-ma** [Tejas1510/Athavani#178]
**Describe the bug**
After signing if, if a user comments on someone else's post, and then try deleting it, they are asked for the admin's password. That means, the comment is not being recognised as the user's own comment.

**To Reproduce**
1. Sign in to the website
2. Post a comment on someone's post
3. Try deleting it
4. User is prompted for admin's password, and a toast notification saying you are trying to delete someone else's comment appears

**Expected behavior**
The user should be allowed to delete their own comment and not prompted for admin's password or shown the error toast notification

**Screenshots**
![image](https://user-images.githubusercontent.com/68962290/113933096-055a4000-97a9-11eb-9c8b-7591f1572a2b.png)
![image](https://user-images.githubusercontent.com/68962290/113933139-1014d500-97a9-11eb-9dbb-4074e9c7e591.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Edge
 - Version: Latest

**Comment by sanjay270899** [comment]
@N-Shar-ma Would you like to work on this issue?

**Comment by N-Shar-ma** [comment]
@sanjay270899 Yes, I've figured out what needs to be changed to fix the bug as well!

**Comment by sanjay270899** [comment]
@N-Shar-ma Go Ahead!
