### ISSUE TITLE
Standard Webpage for the Website

### ISSUE THREAD

**Issue by Tejas1510** [Tejas1510/Athavani#18]
This is a Level-5 issue
You have to create a Separate folder name HomePage and all your code inside it
It should be a full-fledged complete Website and should be responsive
The main designment Part lies with you

**Comment by kanishkaa24** [comment]
I would like to work on this project.

**Comment by antaramunshi** [comment]
i would like to work on this project.Can you assign it to me?

**Comment by Tejas1510** [comment]
@antaramunshi go-ahead
This is a Level-5 issue
You have to create a Separate folder name HomePage and all your code inside it
It should be a full-fledged complete Website and should be responsive
The main designment Part lies with you

**Comment by antaramunshi** [comment]
You mean the frontend right?And should i first send you the wireframe how it should look like?

> @antaramunshi go-ahead
> This is a Level-5 issue
> You have to create a Separate folder name HomePage and all your code inside it
> It should be a full-fledged complete Website and should be responsive
> The main designment Part lies with you

**Comment by kenkirito** [comment]
hii i am good in frontend can you assign me this task

**Comment by kenkirito** [comment]
i would suggest you to make a issue for UI design so that we can decide good front end

**Comment by Tejas1510** [comment]
@antaramunshi yes first show wire frame so we can decide if some changes are required

**Comment by Tejas1510** [comment]
@kenkirito currently one person is assigned the issue
If the issue is not solved you will be the next one
Till then you can give a wireframe on how the website look

**Comment by antaramunshi** [comment]
@Tejas1510 i think we need a logo as well maybe

**Comment by Tejas1510** [comment]
Do you want to create it or Should I create a separate issue

**Comment by Tejas1510** [comment]
@antaramunshi are you working on the issue or will I assign someone?

**Comment by antaramunshi** [comment]
@Tejas1510 yeah, i'm working on it.you'll get it by tonight

**Comment by Tejas1510** [comment]
@antaramunshi Sure no worries
Take your time

**Comment by kanishkaa24** [comment]
Is there any change required? @Tejas1510

**Comment by Tejas1510** [comment]
We have got one home page and we will be taking some features of your website 
I will be guiding you about the same
Currently I am engaged in some work
Till then you can work on other issue or create your own

**Comment by kanishkaa24** [comment]
> We have got one home page and we will be taking some features of your website
> I will be guiding you about the same
> Currently I am engaged in some work
> Till then you can work on other issue or create your own

So I won't be graded for this or the layout that I created earlier for Level 4?

**Comment by Tejas1510** [comment]
You will be

**Comment by chait04** [comment]
assign me this issue no one i working on that.. @Tejas1510 u should remove assignees if they cant respond in 7 days

**Comment by Tejas1510** [comment]
@chait04 Go ahead

**Comment by chait04** [comment]
@Tejas1510 means i have to put the all logic which is in app component to the the Home page component.. is this what u want

**Comment by Tejas1510** [comment]
Just go through the description 
You have to create a website for the project having components like navbar, fotter , features of the projects and other things which are present in a standard website

**Comment by vedikaag99** [comment]
@Tejas1510 Hey, Can I work on this issue?

**Comment by chait04** [comment]
@vedikaag99 im already half way now.. im working on it

**Comment by kenkirito** [comment]
@Tejas1510 is the issue still open

**Comment by Tejas1510** [comment]
NO
