### ISSUE TITLE
Adding animation to component

### ISSUE THREAD

**Issue by Castella1313** [Tejas1510/Athavani#180]
Adding animation to component

Adding animation to these components 

![Screenshot 2021-04-08 at 8 31 10 PM](https://user-images.githubusercontent.com/53293156/114050067-96184500-98a9-11eb-9bfd-60cb9cf8e10b.png)

Animation Like this - 

https://user-images.githubusercontent.com/53293156/114050152-a6c8bb00-98a9-11eb-8cfb-e1385128d8db.mov

**Comment by Castella1313** [comment]
@sanjay270899 May I work on it??

**Comment by Tejas1510** [comment]
Go ahead @Castella1313
