### ISSUE TITLE
Resend OTP for SignUp

### ISSUE THREAD

**Issue by SanskrutiRP** [Tejas1510/Athavani#181]
I think we should provide resend OTP option.

If user fails to enter OTP in some interval of time their should be option to resend the OTP after some time period.

**Comment by SanskrutiRP** [comment]
I would like to work on this will you assign this to me under GSSoC'21.

**Comment by Tejas1510** [comment]
Go ahead @SanskrutiRP

**Comment by SanskrutiRP** [comment]
Thank you!

**Comment by Abhinav0909** [comment]
@Tejas1510  I want to contribute in this issue.

**Comment by ChitvanRamani22** [comment]
@Abhinav0909 go ahead.

**Comment by ChitvanRamani22** [comment]
@Abhinav0909 any updates???

**Comment by Abhinav0909** [comment]
Please give me two more days. I will try to finish it @ChitvanRamani22 sory for the delay.

**Comment by Jassi10000** [comment]
@Abhinav0909 Are you done with the task  ?
What are the updates buddy ?
