### ISSUE TITLE
Multiple Commenting at burst clicking

### ISSUE THREAD

**Issue by AmeyaJain-25** [Tejas1510/Athavani#185]
**Describe the bug**
If we write a comment and click on the comment button continuously, it gets multiple same comments added.

**To Reproduce**
1. Go to 'Comments'
2. Add a comment.
3. Continuously click on the button to send multiple comment.

**Expected behavior**
It should not send multiple comments.

**Screenshots**
![Screenshot from 2021-04-09 13-35-31](https://user-images.githubusercontent.com/66305085/114150095-484b1d80-9939-11eb-8df5-bd81e6bb1233.png)
![Screenshot from 2021-04-09 13-35-16](https://user-images.githubusercontent.com/66305085/114150103-4b460e00-9939-11eb-8541-95cfec80812b.png)

**Additional context**
I would like to work on this issue under GSSOC 21'

**Comment by sanjay270899** [comment]
@AmeyaJain-25 Go Ahead!
