### ISSUE TITLE
Uploading file takes extensions of all types

### ISSUE THREAD

**Issue by AmeyaJain-25** [Tejas1510/Athavani#195]
**Describe the bug**
While uploading the files, it takes up all extenion files.

**To Reproduce**
1. Go to 'Upload button'
2. Upload .py, .pdf, etc extensions
3. See error

**Expected behavior**
It should accept only images extension such as png, jpg, jpeg.

**Screenshots**
If I upload .py file, it doesn't shows the image as it's not a jpg or png type of extension.
![Screenshot from 2021-04-10 13-19-27](https://user-images.githubusercontent.com/66305085/114280298-3ca14900-9a56-11eb-9dc5-eaadb09b4861.png)

**Additional context**
Please assign me this issue under GSSoC21

**Comment by Tejas1510** [comment]
Go ahead @AmeyaJain-25
