### ISSUE TITLE
Create Post Modal

### ISSUE THREAD

**Issue by AmeyaJain-25** [Tejas1510/Athavani#198]
**Is your feature request related to a problem? Please describe.**
The Create Post Memory at the right is taking space. I have an idea that we can shift this into a modal and create memory will open when the button is clicked.
Then user can fill the form and the space of it can occupy another post besides to that.

![Screenshot from 2021-04-11 14-22-13](https://user-images.githubusercontent.com/66305085/114298152-9fd0c100-9ad2-11eb-8bed-e65a08f39dd5.png)

**Describe the solution you'd like**
Inserting the form into a modal and give space for posts. 

**Additional context**
Please assign me this issue under GSSoC 21

**Comment by sanjay270899** [comment]
@AmeyaJain-25 Great! I was also thinking something like this.

Go Ahead!
