### ISSUE TITLE
Design a Logo for the Website

### ISSUE THREAD

**Issue by Tejas1510** [Tejas1510/Athavani#20]
Design a Logo that clearly depicts the meaning of the project

**Comment by kanishkaa24** [comment]
Please assign me this.

**Comment by Aniket31-coder** [comment]
Hey,
I would love to create a logo!

**Comment by Tejas1510** [comment]
The issue is open to all 
The best logo will be merged

**Comment by kanishkaa24** [comment]
![1](https://user-images.githubusercontent.com/71253790/103176837-24d4f900-489b-11eb-9b26-e7e6ed6763fe.png)
Design 1

**Comment by kanishkaa24** [comment]
![3](https://user-images.githubusercontent.com/71253790/103176850-374f3280-489b-11eb-9aff-5bd034f824bb.png)
Design 2

**Comment by kanishkaa24** [comment]
If you like any of these, lmk.

**Comment by Aniket31-coder** [comment]
Hey!
I have made two logos one in Marathi and the other in English, please let me know, if any changes are required!
![Add a heading (1)](https://user-images.githubusercontent.com/55101835/103192971-b9257700-4900-11eb-928d-61a442920b25.png)
![Add a heading (2)](https://user-images.githubusercontent.com/55101835/103192975-bb87d100-4900-11eb-8a4f-2509b5eab7d1.png)

**Comment by Tejas1510** [comment]
@kanishkaa24 and @Aniket31-coder add your logo inside the assets folder which is inside the homepage folder by creating a new PR I will merge it

**Comment by kanishkaa24** [comment]
@Tejas1510 
I am not able to understand how to upload an image. Can you help me out here ?

**Comment by Tejas1510** [comment]
just have a folder name images add your image in that and img src-"" add your image URL 
Now while creating a PR add your complete folder having image folder HTML file and css file

**Comment by kanishkaa24** [comment]
@Tejas1510 
Please add the labels to my pull request too.

**Comment by musavveer** [comment]
Even I would like to contribute!

**Comment by Swapnil-Gaur** [comment]
Is the issue is still open.
I wanna contribute  in it, Can I @Tejas1510?

**Comment by Tejas1510** [comment]
Go ahead @Swapnil-Gaur

**Comment by musavveer** [comment]
@Tejas1510 where should I save the logo?

**Comment by Tejas1510** [comment]
Inside the image folder which is inside the homepage folder

**Comment by Swapnil-Gaur** [comment]
![c3b4b741-ba93-4e20-93f6-a7411f5f7639_200x200](https://user-images.githubusercontent.com/71397235/103518436-c4951700-4e99-11eb-8f1d-fdda1caa63af.png)

@Tejas1510  please check logo.
