### ISSUE TITLE
Comments Section

### ISSUE THREAD

**Issue by AmeyaJain-25** [Tejas1510/Athavani#203]
**Is your feature request related to a problem? Please describe.**
When comments number is too high or suppose 100, then the comments will show all 100 when comments section is opened.

**Describe the solution you'd like**
Either shifting the comments to new page or a modal.

**Describe alternatives you've considered**
My suggestion is to shift it to the modal.

**Additional context**
Please assign me this issue under GSSoC21

**Comment by sanjay270899** [comment]
@AmeyaJain-25 any update?

**Comment by AmeyaJain-25** [comment]
Yes,
Just came at the end part.
Will be making PR by tomorrow.
Will that work?
