### ISSUE TITLE
Show Outline Like/Dislike Icon when user have not Like/Dislike a post

### ISSUE THREAD

**Issue by sanjay270899** [Tejas1510/Athavani#204]
Use these icons:

`import ThumbUpAltOutlinedIcon from '@material-ui/icons/ThumbUpAltOutlined';`

`import ThumbDownAltOutlinedIcon from '@material-ui/icons/ThumbDownAltOutlined';`

**Comment by Cgoyal48** [comment]
> Use these icons:
> 
> `import ThumbUpAltOutlinedIcon from '@material-ui/icons/ThumbUpAltOutlined';`
> 
> `import ThumbDownAltOutlinedIcon from '@material-ui/icons/ThumbDownAltOutlined';`

@sanjay270899 please assign this issue under gssoc21 to me.
