### ISSUE TITLE
[Bug] Comment Time

### ISSUE THREAD

**Issue by sanjay270899** [Tejas1510/Athavani#208]
Bug: Time in comments is always showing `a few seconds ago`.

![image](https://user-images.githubusercontent.com/43892590/116011446-c1898680-a642-11eb-802b-b6b8c04259db.png)

**Comment by GuptaTanisha** [comment]
Please assign this to me.

**Comment by sanjay270899** [comment]
@GuptaTanisha update?

**Comment by GuptaTanisha** [comment]
> @GuptaTanisha update?

I am not able to sign up. Can't generate the OTP.

**Comment by GuptaTanisha** [comment]
@sanjay270899 I tried to fix the bug. As I am not able to sign up. I have not verified whether the bug is fixed or not. Please check and update whether it is fixed or not.
