### ISSUE TITLE
Move all options to a fixed Left Nav Bar

### ISSUE THREAD

**Issue by sanjay270899** [Tejas1510/Athavani#216]
Each item of Left Fixed Navbar should have a relevant icon and name.

- Home
- Create Post
- Filters
- Subscribe
- Profile
- Logout

![image](https://user-images.githubusercontent.com/43892590/117303322-33ab6800-ae9a-11eb-8c2d-346e5fff0de5.png)

**Comment by Cgoyal48** [comment]
@sanjay270899 Kindly assign this issue to me under GSSOC.

**Comment by sanjay270899** [comment]
@Cgoyal48 Go Ahead!
