### ISSUE TITLE
Adding GIF to readme

### ISSUE THREAD

**Issue by ShubhamSj07** [Tejas1510/Athavani#217]
**Is your feature request related to a problem? Please describe.**
I have designed a GIF which looks pretty good :)
Would love to add to readme file

![Athavani-GIF](https://user-images.githubusercontent.com/56510414/117333785-e689bf00-aeb6-11eb-8b57-e98c50f22b4e.gif)

Pls assign me this issue

**Comment by Tejas1510** [comment]
Go ahead @ShubhamSj07
