### ISSUE TITLE
Divide Header in two parts

### ISSUE THREAD

**Issue by sanjay270899** [Tejas1510/Athavani#220]
Wireframe:
![image](https://user-images.githubusercontent.com/43892590/117530930-7c2f6680-affd-11eb-8e46-3fc8569f2564.png)

**Comment by Cgoyal48** [comment]
@sanjay270899 I would like to work on this issue, kindly please assign it to me.

**Comment by AmeyaJain-25** [comment]
If it's not done? Then can I work on this issue?
@sanjay270899 @Cgoyal48

**Comment by Cgoyal48** [comment]
> If it's not done? Then can I work on this issue?
> @sanjay270899 @Cgoyal48

I have done it but @sanjay270899 is not responding to it

**Comment by Tejas1510** [comment]
@Cgoyal48 have you generated the pull request for this issue

**Comment by Cgoyal48** [comment]
@Tejas1510 No

**Comment by Tejas1510** [comment]
If you are done with the work you can generate a pull request, I and @sanjay270899 will review it till the end of the day
If you are having any doubt you can ask out here

**Comment by Cgoyal48** [comment]
Okay
