### ISSUE TITLE
Toogling between Fav and All posts

### ISSUE THREAD

**Issue by AmeyaJain-25** [Tejas1510/Athavani#222]
**Is your feature request related to a problem? Please describe.**
The favourite and all post button is not looking good and is at very center at start.
Currently if new user comes, he/she may doesn't know that whether on clicking fav button the all posts button comes or not, etc

**Describe the solution you'd like**
Make it in a sequential and good looking manner, I suppose to have a toggle button at RIGHT CORNER. It will toggle between my fav and all posts. 

**Additional context**
Please assign me this issue under GSSoC21'

**Comment by Tejas1510** [comment]
Go ahead @AmeyaJain-25
