### ISSUE TITLE
Abrupt Component Change

### ISSUE THREAD

**Issue by ashishnagpal2498** [Tejas1510/Athavani#226]
**Describe the bug**
The SignUp component gets switched up to SignIn component, abruptly.

**To Reproduce**
1. Login to the app for the first time. You will able to see blue colored notification.
2. Click on 'Sign Up' button before the notification ends. (Within 2 secs)

**Possible Solution** 
The state of notification is in queue which is to be cleared, when the component has changed. 
Or 
Put the Notification in parent component and manage the state of Notification globally in parent component, by dispatching an action.

**Comment by GuptaTanisha** [comment]
Can I work on this?

**Comment by GuptaTanisha** [comment]
I am not able to sign up. Not getting any OTP. How to sign up?

**Comment by AshuKV** [comment]
Can I work on this issue under GSSoC'21? Kindly assign it to me.

**Comment by ashishnagpal2498** [comment]
Will fix that OTP issue. Well this issue doesn't require login. Try replicating it and let me know if @GuptaTanisha if you would like to work on this issue ?

**Comment by GuptaTanisha** [comment]
@ashishnagpal2498 I would like to work on this.

**Comment by sanjay270899** [comment]
> I am not able to sign up. Not getting any OTP. How to sign up?

Maybe token got expired. I will re-generate it.
