### ISSUE TITLE
[Open to All] Add your memory

### ISSUE THREAD

**Issue by Tejas1510** [Tejas1510/Athavani#26]
Add any of your memory 
Image is a must while creating the memory and it should be something that signifies that
Spam Memory is not allowed
It should have a proper name, title, message, and Image else you won't we awarded any points
Go to Main Site and Create Your Memory: https://memoriestejastapas.netlify.app/

**Comment by kanishkaa24** [comment]
Do we need to add a memory to solve this issue ?

**Comment by Tejas1510** [comment]
Yes

**Comment by kanishkaa24** [comment]
@Tejas1510 Assign me please.

**Comment by Tejas1510** [comment]
It is open to all anyone can work
I won't be assigning anyone

**Comment by musavveer** [comment]
I would like to work on it.

**Comment by kanishkaa24** [comment]
![Screenshot (128)](https://user-images.githubusercontent.com/71253790/103213275-2eaa3b00-4933-11eb-90b5-ebcd010ca4ab.png)
Done

**Comment by Tejas1510** [comment]
Great !

**Comment by himanshu007-creator** [comment]
done! 
![Picture1](https://user-images.githubusercontent.com/65963997/103370949-32d18680-4af4-11eb-83bd-0e5254c3974d.png)

**Comment by Tejas1510** [comment]
Good Work @himanshu007-creator

**Comment by himanshu007-creator** [comment]
> Good Work @himanshu007-creator

mam now we have to send a PULL REQUEST with ss of this, or we will be awarded points automatically?

**Comment by Tejas1510** [comment]
You will get it directly @himanshu007-creator 
and it is man not mam  😅

**Comment by himanshu007-creator** [comment]
> You will get it directly @himanshu007-creator
> and it is man not mam 😅

Okay @Tejas1510  man!😂👍🏽

**Comment by shubhraagarwal** [comment]
Added a memory!!! 
How are the points going to be assigned for this??
![image](https://user-images.githubusercontent.com/67220475/103790895-c9a7c100-5067-11eb-85e4-cea270b755ff.png)

**Comment by musavveer** [comment]
@Tejas1510 Why did you close this?

**Comment by Tejas1510** [comment]
It is not having any points as you just needed to add very small information in card and according to organiser it can be considered as a contribution
