### ISSUE TITLE
UI not proper for Post if long content.

### ISSUE THREAD

**Issue by AmeyaJain-25** [Tejas1510/Athavani#279]
If we post a memory with long content, then it allows. 
But the issue is that it's shown with the whole content and it scrolls for the whole page as shown below. Also it affects it's sibling post height.
Note: The post is without opening the read more button.
![Screenshot from 2021-05-31 18-13-03](https://user-images.githubusercontent.com/66305085/120195015-ee314f00-c23b-11eb-9a52-5751e1d7e295.png)

I think that this should be limit to the content to be shown.

Please assign me this issue.

**Comment by Divyanshj** [comment]
Can I contribute to this issue ?
please consider assigning
