### ISSUE TITLE
[Bug] Make button of form at center

### ISSUE THREAD

**Issue by Tejas1510** [Tejas1510/Athavani#28]
![image](https://user-images.githubusercontent.com/64543913/103208338-678fe300-4926-11eb-8023-40c9f278c819.png)
In mobile view, the buttons are not placed at the center

**Comment by musavveer** [comment]
Hi!
Please assign me this issue. I would like to give it a shot.

**Comment by Tejas1510** [comment]
Go for it @musavveer

**Comment by shubhraagarwal** [comment]
Can I give this a try?

**Comment by Tejas1510** [comment]
Currently, a person is assigned if the issue is not solved then I will assign it to you
