### ISSUE TITLE
Add smooth transition to login and send otp buttons

### ISSUE THREAD

**Issue by supzi-del** [Tejas1510/Athavani#289]
When buttons are hovered upon, they are kind of harsh, so I would like to add a smooth transition to make it look nicer.

**Comment by Tejas1510** [comment]
@AmeyaJain-25 please have a look at this and assign accordingly

**Comment by AmeyaJain-25** [comment]
@supzi-del 
Can you please elaborate a bit more on which buttons are harsh. Or some screenshots of that buttons.

**Comment by AmeyaJain-25** [comment]
Sure @supzi-del 
Go ahead.
Also try keeping the color theme of the application relatable.

**Comment by supzi-del** [comment]
Sure. I am working on it under LGM SOC'21. Can you please add the label?
