### ISSUE TITLE
Logout Issue

### ISSUE THREAD

**Issue by AmeyaJain-25** [Tejas1510/Athavani#291]
**Describe the bug**
User cannot logout. On clicking on logout, it gets an error.

**To Reproduce**
1. Go to 'Athavani'
2. Signin
3. Click on Logout

**Expected behavior**
User should properly logout

**Screenshots**
![Screenshot from 2021-06-10 13-22-12](https://user-images.githubusercontent.com/66305085/121488648-e36f7a80-c9f0-11eb-9006-df2c59b39f75.png)

**Additional context**
Anyone wishing to grab this issue are welcome.

**Comment by jayant766** [comment]
can i work on it?

**Comment by AmeyaJain-25** [comment]
Sure go ahead

**Comment by AmeyaJain-25** [comment]
Any update @jayant766

**Comment by jayant766** [comment]
@AmeyaJain-25 working on it. Just give me one more day.

**Comment by ChitvanRamani22** [comment]
@jayant766 any updates?

**Comment by ChitvanRamani22** [comment]
@jayant766 are you working on this issue?

**Comment by soumalyatheking22012001** [comment]
I can also work on this considering the last comment was 4 days ago I think no one is working

**Comment by ChitvanRamani22** [comment]
@soumalyatheking22012001 any updates??

**Comment by ChitvanRamani22** [comment]
> I can also work on this considering the last comment was 4 days ago I think no one is working

Are u working?

**Comment by ujju20** [comment]
Can I work on this issue?

**Comment by ChitvanRamani22** [comment]
@ujju20 can you please update on your work?
