### ISSUE TITLE
Improve the social media icons design

### ISSUE THREAD

**Issue by supzi-del** [Tejas1510/Athavani#295]
**Is your feature request related to a problem? Please describe.**
The social media icons below "contact us" can be highlighted to make it look good

**Describe the solution you'd like**
An animation scale of 1.1 can be added and circular background can be white.

**Comment by AmeyaJain-25** [comment]
Sure @supzi-del, go ahead 👍🏻

**Comment by supzi-del** [comment]
Hey! Can you please tell me in which file is the CSS related to social icons located?

**Comment by AmeyaJain-25** [comment]
> Hey! Can you please tell me in which file is the CSS related to social icons located?

It's in the components/Footer folder.
You can see the footer.js file and style.css
