### ISSUE TITLE
Improve the UI of Create memory form

### ISSUE THREAD

**Issue by ambalika24** [Tejas1510/Athavani#297]
I want to improve the UI of memory form to make it more appealing.
I want to change it's layout and styling.
@Tejas1510 please assign this issue to me under LGM SOC 21

**Comment by AmeyaJain-25** [comment]
Sure, Go ahead @ambalika24 
Discussing the UI or the change for the memory form before implementing it would be great.

**Comment by AmeyaJain-25** [comment]
@ambalika24 
Any update?

**Comment by ambalika24** [comment]
Sir, there is only one minor change left to do. i will send you my task by today itself.
