### ISSUE TITLE
It seems (signUp page )unresponsive in other views 

### ISSUE THREAD

**Issue by Kartikey0205** [Tejas1510/Athavani#298]
Footer and sign up form overlap each other

Please assign me this under Lgm SoC'21 @Tejas1510 
![Screenshot_2021-06-12-09-34-07-53](https://user-images.githubusercontent.com/66429038/121764483-f3f33280-cb61-11eb-98b0-09fb002f6947.jpg)

**Comment by AmeyaJain-25** [comment]
@Kartikey0205 
This issue is solved over here.
#290 
The PR is also made. #294 

You can take a fresh pull to see the issue resolved.

Anyways, You can go with other issues.
Keep contributing 💯
