### ISSUE TITLE
Updating README.md Section

### ISSUE THREAD

**Issue by codeaholic-shub** [Tejas1510/Athavani#299]
**Is your feature request related to a problem? Please describe.**
I want to add "Lets Grow More" PNG image in README.md section for more captivating

**Additional context**
I an the participant of LGM-SOC 21 , so kindly assign this issue to me !
![121303829-28c07900-c919-11eb-8cf2-afd39b5c54ab png (781×261) - Google Chrome 12-06-2021 11_37_53](https://user-images.githubusercontent.com/65807708/121766987-29ece280-cb73-11eb-8c73-e851e4d218f5.png)

**Comment by codeaholic-shub** [comment]
Hey @Tejas1510 ,
Kindly assign this issue ,
So , I can work on it as soon as possible !

**Comment by AmeyaJain-25** [comment]
Yes, Go ahead @codeaholic-shub 👍🏻

**Comment by jayant766** [comment]
Kindly assign this issue ,
So , I can work on it as soon as possible !
