### ISSUE TITLE
Firebase SIgnIn

### ISSUE THREAD

**Issue by AmeyaJain-25** [Tejas1510/Athavani#301]
Currently the application supports the google console signin. And this is creating logout issues and setup issues for many of us.
So, we are planning to shift the authentication of google signin to Firebase Signin with google.

Things to be done:
1. Remove the code base of google console authentication.
2. Add firebase sign in with google option.

Any one wishing to can solve this issue.

**Comment by ritik-vashist** [comment]
I can work on this issue.
@sanjay270899 , @AmeyaJain-25 sir could you please assign this task to me?

**Comment by ChitvanRamani22** [comment]
@ritik-vashist go ahead!

**Comment by ritik-vashist** [comment]
@AmeyaJain-25 , @ChitvanRamani22  Should I work on user verification also on the backend or I could do is  use proper signing and sign up by use of firebase in this issue. And later create a second issue that will verify the user?

**Comment by AmeyaJain-25** [comment]
Yes.
Current need is simply the firebase Signin.
You can do this in this issue

**Comment by ritik-vashist** [comment]
@AmeyaJain-25 @ChitvanRamani22 @Jassi10000 @Tejas1510  sir, 
I am having a query. I.e-  in this issue I have to use firebase auth config file. For testing I can use mine but for the real deployment project admins have to provide that Or guide me what to do with that?

**Comment by AmeyaJain-25** [comment]
@ritik-vashist 
The verification through backend with email, etc can be done in another issue.
Gor for this once you finish this one

All the best 💯

**Comment by AmeyaJain-25** [comment]
> @AmeyaJain-25 @ChitvanRamani22 @Jassi10000 @Tejas1510 sir,
> I am having a query. I.e- in this issue I have to use firebase auth config file. For testing I can use mine but for the real deployment project admins have to provide that Or guide me what to do with that?

You can create your own firebase details.
Once you are complete with your PR, just create a env.example file and provide the details to be given in that.


You can write the details in firebaseConfig.js file as,

var = {
firevaseAuthId: process.env.REACT_APP_AUTHID
........}


Like this you can create the config file and then push the code.
So, that every user can just put the credentials directly in the env file and access the firebase login
