### ISSUE TITLE
Sidebar UI

### ISSUE THREAD

**Issue by AmeyaJain-25** [Tejas1510/Athavani#305]
We wanna change the simple sidebar to something like [this](https://demos.creative-tim.com/material-dashboard-react/#/admin/dashboard)

Please have a look to the link above and try to implement the same and keeping the note of the color matching.

Anyone wishing to take this is welcomed.

**Comment by ankh77sb** [comment]
I would like to work on this issue.. kindly assign

**Comment by nimishbhandari** [comment]
I would like to work on this issue please

**Comment by ChitvanRamani22** [comment]
@nimishbhandari as we work on first come first server basis so i have to assign it to @ankh77sb .
@nimishbhandari till then feel free to take up any other issue.

**Comment by ankh77sb** [comment]
@AmeyaJain-25 .. im having issues in setting up..

**Comment by AmeyaJain-25** [comment]
> @AmeyaJain-25 .. im having issues in setting up..

Have you joined the slack channel?

**Comment by AmeyaJain-25** [comment]
Join the channel of Athvani project.
And just ping me over there. I'll resolve the set-up

**Comment by ChitvanRamani22** [comment]
@ankh77sb are you working on this?

**Comment by ankh77sb** [comment]
im unable to override some of the properities.. u may reassign to some other member

**Comment by ChitvanRamani22** [comment]
@ankh77sb If you have any issues you can always ask here or on slack.

**Comment by Navdeepsingh4298** [comment]
I've seen the template i can do it. I can do it using material ui. please assign me.

**Comment by Navdeepsingh4298** [comment]
could you tell me do i have to make exactly same sidebar as shown in https://demos.creative-tim.com/material-dashboard-react/#/admin/dashboard

**Comment by AmeyaJain-25** [comment]
Yes @Navdeepsingh4298

**Comment by AmeyaJain-25** [comment]
Also if possible, try the color scheme of the project. If it suits better than this, then you can apply that

**Comment by Navdeepsingh4298** [comment]
Ok i'll try my best.
