### ISSUE TITLE
Add links to badges

### ISSUE THREAD

**Issue by Umesh-01** [Tejas1510/Athavani#306]
The badges (see the below image) in the README.md file doesn't contain any link to the related web pages and without them they are of no use.

![image](https://user-images.githubusercontent.com/83420185/121814815-9c9fb000-cc90-11eb-99dd-0548d26e535c.png)

I want to  add links to the badges so that anyone can go to the webpages after clicking on them.

**Comment by Umesh-01** [comment]
@Tejas1510 sir should I go ahead to make changes??

**Comment by ChitvanRamani22** [comment]
@Umesh-01 go ahead!!
