### ISSUE TITLE
Remove Warnings

### ISSUE THREAD

**Issue by ChitvanRamani22** [Tejas1510/Athavani#307]
**Describe the bug**
On starting the project there are a lot of warnings that appear in the command-prompt which need to be removed as they do not look good.

**Comment by archanakumari-ak** [comment]
@ChitvanRamani22 I would like to work on this issue.

**Comment by ChitvanRamani22** [comment]
@archanakumari-ak Go Ahead!!

**Comment by ChitvanRamani22** [comment]
@archanakumari-ak any updates?

**Comment by archanakumari-ak** [comment]
The warning I faced in the command prompt was : **"JsonWebTokenError: jwt malformed"**

![Capture758](https://user-images.githubusercontent.com/64682846/122549359-01238c00-d050-11eb-9225-c8f7558cc92e.PNG)

It was taking **token="null"** so I added if/else to check that on **Line 14** in **server/middleware/loginRequired.js**.

![Capture757](https://user-images.githubusercontent.com/64682846/122549389-0a145d80-d050-11eb-90a7-50e0dc76ccfb.PNG)

If you are facing any other warning, please tell.

**Comment by ChitvanRamani22** [comment]
@archanakumari-ak seems like you have misunderstood the issue. I want you to remove the warnings that you see in the command prompt when you go inside client folder and then do npm start.

**Comment by archanakumari-ak** [comment]
@ChitvanRamani22 I am sorry on my part, will do the changes soon and update the PR.

**Comment by ChitvanRamani22** [comment]
@archanakumari-ak no worries
