### ISSUE TITLE
Fresh styling of Sign-in and sign-up Pages.

### ISSUE THREAD

**Issue by nimishbhandari** [Tejas1510/Athavani#310]
-- I want to give these auth pages a new fresh look which will look more attractive. 
-- I will vertically and horizontally center align the form.
-- Will use better colours.
-- Will use better fonts.

**Comment by ChitvanRamani22** [comment]
@nimishbhandari go ahead!

**Comment by ChitvanRamani22** [comment]
@nimishbhandari any updates?

**Comment by ChitvanRamani22** [comment]
@nimishbhandari unassigning due to no response.

**Comment by heet-kumar** [comment]
@ChitvanRamani22 will you assign me this issue and what are the requirements are there from your side .

**Comment by ChitvanRamani22** [comment]
@heet-kumar you can think of the ideas for your side and share them here.

**Comment by heet-kumar** [comment]
@ChitvanRamani22  ok and I am working under LGM-SOC'21

**Comment by heet-kumar** [comment]
@ChitvanRamani22 which one is your back-ground image and header which one is correct .
1 . which showing in this https://athavani.vercel.app/signin
![Screenshot (657)](https://user-images.githubusercontent.com/78725162/122945651-5801cc00-d396-11eb-8457-8a76abe17cd7.png)

2.  or this one which is shown below in vercel app
![Screenshot (656)](https://user-images.githubusercontent.com/78725162/122944784-baa69800-d395-11eb-9fc7-4a34144fa365.png)

**Comment by ChitvanRamani22** [comment]
@heet-kumar 2nd one is looking nice ..go ahead

**Comment by ChitvanRamani22** [comment]
@heet-kumar any further updates??

**Comment by heet-kumar** [comment]
@ChitvanRamani22 sign in page will looks like any more modification you required then tell .
![Screenshot (660)](https://user-images.githubusercontent.com/78725162/123355883-3108ed00-d584-11eb-815f-8e36699dfc8e.png)

**Comment by soumalyatheking22012001** [comment]
Put an assigned label in this issue

**Comment by ChitvanRamani22** [comment]
> @ChitvanRamani22 sign in page will looks like any more modification you required then tell .
> ![Screenshot (660)](https://user-images.githubusercontent.com/78725162/123355883-3108ed00-d584-11eb-815f-8e36699dfc8e.png)
> 

@heet-kumar increase tye margin top of email input box so that the whole form shifts a little more down.

**Comment by heet-kumar** [comment]
ok sure

**Comment by heet-kumar** [comment]
@ChitvanRamani22 completed the Styling of the SignIn and SignUp page as you can see below. any changes are required then tell.
Sign In page :
![Screenshot (692)](https://user-images.githubusercontent.com/78725162/123523235-092e9c00-d6e0-11eb-90af-dc07f2618c34.png)
 Sign Up page :
![Screenshot (691)](https://user-images.githubusercontent.com/78725162/123523254-28c5c480-d6e0-11eb-84c0-f4fe34a41b22.png)

**Comment by heet-kumar** [comment]
@ChitvanRamani22 also they both are responsive as well

**Comment by heet-kumar** [comment]
@ChitvanRamani22 also reply as soon as possible.

**Comment by ChitvanRamani22** [comment]
> > @ChitvanRamani22 sign in page will looks like any more modification you required then tell .
> > ![Screenshot (660)](https://user-images.githubusercontent.com/78725162/123355883-3108ed00-d584-11eb-815f-8e36699dfc8e.png)
> > 
> 
> @heet-kumar increase the margin top of email input box so that the whole form shifts a little more down.

@heet-kumar do this with signup also and generate the pr.

**Comment by heet-kumar** [comment]
@ChitvanRamani22 done all updates you need ss or I should go for creating pr .

**Comment by ChitvanRamani22** [comment]
@heet-kumar just go agead with the pr

**Comment by heet-kumar** [comment]
ok by tomorrow morning I will do it

**Comment by heet-kumar** [comment]
@ChitvanRamani22 is it ok check it

**Comment by ChitvanRamani22** [comment]
@heet-kumar Have u generated a pr??

**Comment by heet-kumar** [comment]
@ChitvanRamani22 yes I have created check it , is it not visible
