### ISSUE TITLE
Need Refactoring in README.md

### ISSUE THREAD

**Issue by Rishabhraghwendra18** [Tejas1510/Athavani#312]
**Describe the bug**
In `Readme.md` file , under `Open Source Program` section , first two logos are added using `<img/>` tag but the last one which is of `Let's Grow More Summer of Code` , is added using markdown syntax. Take a look:
```## 📢  Open Source Program

### This Project is a part of the following Open Source Program

<img src ="https://github.com/Tejas1510/Athavani/blob/master/assets/Images/devscriptcode.png" alt ="Devscript Winter of Code"></img>
<img src = "https://github.com/Tejas1510/Athavani/blob/master/assets/Images/gssoc.png" alt = "GirlScript Summer of Code"></img>
![Lets Grow More Summer of Code](https://user-images.githubusercontent.com/60106112/121303829-28c07900-c919-11eb-8cf2-afd39b5c54ab.png)
```
**Solution**
For sake of Uniformity throughout the section . I will like to add the last one's logo using `<img/>` , just like other .

**Comment by Rishabhraghwendra18** [comment]
_I will like to work on this issue under LGMSOC_

**Comment by ChitvanRamani22** [comment]
@Rishabhraghwendra18 go ahead!!
