### ISSUE TITLE
SignIn with google not working

### ISSUE THREAD

**Issue by ayushkwal** [Tejas1510/Athavani#313]
**Describe the bug**
On signin, an easy click for signin with google is not created.

**To Reproduce**
1. Go to 'Website Login Page'
2. See G+ button not working

**Expected behavior**
on clicking that button, it should logged in. 

**Additional context**
Please give me a chance to make this button using Passport

**Comment by ChitvanRamani22** [comment]
@ayushkwal go ahead!!

**Comment by rushikadivar** [comment]
I would like to work on this issue to get into to login page button. Please assign me

**Comment by ChitvanRamani22** [comment]
@rushikadivar the issue is already assigned lets wait for sometime for @ayushkwal to respond .
Till then feel free to take up other issues which are not assigned.
Thanks.

**Comment by rushikadivar** [comment]
Okay, looking for other issues! and I want to share my idea that the signing system should expect like when user get to log in (sign in)
firstly it will check to our database that it is there or the user can directly signing using google auth by clicking the G+ button.
is this a right way?

**Comment by ChitvanRamani22** [comment]
@ayushkwal any updates?

**Comment by ayushkwal** [comment]
Yes, will pull till tomorrow.

**Comment by ChitvanRamani22** [comment]
@ayushkwal any further updates??

**Comment by ayushkwal** [comment]
Someone already implemented it through firebase.
