### ISSUE TITLE
Creating 404 page for website. 

### ISSUE THREAD

**Issue by ritik-vashist** [Tejas1510/Athavani#314]
Currently website is not having 404 page. So i would like to add this page to it by shifting app.js to different components. And bind  the routes accordingly.

**Comment by ritik-vashist** [comment]
@AmeyaJain-25  sir i request you to assign this task to me.

**Comment by ritik-vashist** [comment]
It would be better if your give any design layout selected by the project team.

**Comment by ChitvanRamani22** [comment]
@ritik-vashist go ahead!!
Will send you a template.

**Comment by ChitvanRamani22** [comment]
![20210616_165948.jpg](https://user-images.githubusercontent.com/68965499/122211456-634f8600-cec4-11eb-9409-ab1d0385a1dd.jpg)
![20210616_165935.jpg](https://user-images.githubusercontent.com/68965499/122211462-65194980-cec4-11eb-8cbf-f85904f671bf.jpg)
@ritik-vashist you can go with any one of them.
But try to follow the color theme.

**Comment by ChitvanRamani22** [comment]
@ritik-vashist which tempelate have you choosen?

**Comment by ritik-vashist** [comment]
I have choosen second template, due to some family issue and end sem exams work is delayed by a week I hope I will complete it by this week. 
Sorry for the inconvenience caused by my side.

**Comment by ChitvanRamani22** [comment]
> I have choosen second template, due to some family issue and end sem exams work is delayed by a week I hope I will complete it by this week. 
> Sorry for the inconvenience caused by my side. 

@ritik-vashist no worries, take your time.

**Comment by ritik-vashist** [comment]
@ChitvanRamani22 ma'am you could assign this task to someone else as i am stuck in some family matter. Sorry for the inconvenience caused by my side.

**Comment by Navdeepsingh4298** [comment]
I would like to do this. i've read the conversation. second template need to be made. i can do it.

**Comment by Navdeepsingh4298** [comment]
i have seen somebody already added error404 page 5 months ago, but that doesn't seem working.

**Comment by ChitvanRamani22** [comment]
> i have seen somebody already added error404 page 5 months ago, but that doesn't seem working.
> 

Yes go ahead

**Comment by AmeyaJain-25** [comment]
> i have seen somebody already added error404 page 5 months ago, but that doesn't seem working.

Actually the error 404 works properly, but if you see the app.js code, the Switch from react-router-dom is used somewhere at center and the sidebar and navbar is outside of it. Hence, if you go to any random url after base path, it shows the sidebar and navbar with middle part empty
