### ISSUE TITLE
Crappy Design

### ISSUE THREAD

**Issue by ayushkwal** [Tejas1510/Athavani#316]
The User Interface is very crappy, working fine but not looking **attractive** .
I want to change its design that will make it attractive and responsive.
**Toasts** of React are very common in websites.
Instead of Toasts, showing errors on form itself is good.

Responses recieved from server are very **weird** in looking.
Give me a chance to make it attractive enough.

Big Footer, glossy colours, no responsiveness making it so bad.
Assign me this task, I will make it so attractive and responsive as well.\
In addition, I will add fonts, animations, transitions and many more without any external dependencies.

**Comment by ChitvanRamani22** [comment]
Great idea!!
Go ahead @ayushkwal !

**Comment by ayushkwal** [comment]
What if we do contributions and approved by you?
Will we also get internship or full time opportunity or it is for knowledge
purpose only?

**Comment by ChitvanRamani22** [comment]
@ayushkwal this program is mainly meant for learning but we will soon have a leaderboard for participants. You will surely get some perks if you end up among the top performers , but otherwise also you will recieve a participation certificate.
But again the main take away is learning.

**Comment by ayushkwal** [comment]
Hello,
I have changed design of front login and signup. 
#327 is my code please assign me there and review it.
I will make more changes if you like it.

**Comment by ChitvanRamani22** [comment]
@ayushkwal i appreciate your efforts.
But can you please have a look at this.
![20210618_102650.jpg](https://user-images.githubusercontent.com/68965499/122508674-fbae4d80-d01f-11eb-8ff3-870367e96b9c.jpg)
