### ISSUE TITLE
[Critical Bug] User can update other users post. 

### ISSUE THREAD

**Issue by sanskarbansal** [Tejas1510/Athavani#320]
**A clear and concise description of what the bug is.**
User can provide the _id of other user's post and update it without any authorisation. 
**To Reproduce**
1. Create a post with your user, get someone else's post '_id' from database. 
2. Intercept Requests using BurpSuit.
3. Delete the post which you just created in Step 1.
3.  Change the post id with anybody else post id in delete request in burpsuit and Click on Forward.... .  
4. That's it.

**Expected behavior**
It should throw an error that post id malformed or something like this.

**Comment by ChitvanRamani22** [comment]
@sanskarbansal great go ahead!

**Comment by sanskarbansal** [comment]
@ChitvanRamani22 please review my PR.
