### ISSUE TITLE
Some git commands need to be added in Readme file

### ISSUE THREAD

**Issue by Shaishav0507** [Tejas1510/Athavani#325]
**Is your feature request related to a problem? Please describe.**

Hey @Tejas1510 
I would like to add some more git commands in readme file.
Please assign it to me.
Thanks

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by ChitvanRamani22** [comment]
@Shaishav0507 it would be more convenient if you provide some examples of tge commands that you want to add.

**Comment by Shaishav0507** [comment]
Git remote add upstream.
Pull upstream
Git status

**Comment by Jassi10000** [comment]
@Shaishav0507  I don't think you will require this , by creating a new branch you can easily work 
upstream  concept we don't suggest the participants to do

**Comment by Shaishav0507** [comment]
Ok
