### ISSUE TITLE
[Form Validation] 

### ISSUE THREAD

**Issue by Tejas1510** [Tejas1510/Athavani#33]
Add a form validation such that the user cannot create a memory unless all the fields are completely field including the image
if even anyone is remaining then he should be promoted to fill that unless his memory will not be created

**Comment by sanjay270899** [comment]
I would like to work on this.

**Comment by Tejas1510** [comment]
Go ahead @sanjay270899

**Comment by sanjay270899** [comment]
You can now close this issue if you wish.
