### ISSUE TITLE
Add Custom Scrollbar

### ISSUE THREAD

**Issue by priyaastha** [Tejas1510/Athavani#334]
**Is your feature request related to a problem? Please describe.**
I want to add a custom scroll bar that matches the UI of the website

**Comment by priyaastha** [comment]
Please assign this issue under LGMSOC21
@sanskarbansal @ashishnagpal2498 @Supriya1702 @abhay27chauhan

**Comment by ChitvanRamani22** [comment]
@priyaastha i think you havn"t tagged the right people.

**Comment by priyaastha** [comment]
Sorry and thanks

**Comment by ChitvanRamani22** [comment]
@priyaastha any updates??

**Comment by priyaastha** [comment]
Hey, should I apply this custom scrollbar on all the pages?
![Athavani - Google Chrome 03-07-2021 00_24_41](https://user-images.githubusercontent.com/55706563/124317686-2efee980-db95-11eb-9cd4-3275771eb086.png)
According to me, some of the files that may be changed to apply the scrollbar:
client/src/index.css
client/src/App.css
client/src/components/Auth/Forgot/Forgot.module.css
client/src/components/Auth/ResetPassword/ResetPassword.module.css
client/src/components/Auth/SignIn/SignIn.module.css
client/src/components/Auth/SignUp/SignUp.module.css
and there are many more.
So, if there's any file which you think should not be changed please tell me. Thanks a lot.

**Comment by ChitvanRamani22** [comment]
@priyaastha Why are all these files being changed i think we need to change only app.css

**Comment by priyaastha** [comment]
Ok, sir. Thanks for the help.
