### ISSUE TITLE
Add git code- upstream & remote in readme

### ISSUE THREAD

**Issue by supzi-del** [Tejas1510/Athavani#344]
**Is your feature request related to a problem? Please describe.**
After cd and before making new branch, there is no code -- git remote add upstream

**Describe the solution you'd like**
Add the git code to pull from upstream master

**Describe alternatives you've considered**

**Additional context**
Reference from another project:-
![Screenshot (337)](https://user-images.githubusercontent.com/78655439/124227812-e14c9780-db28-11eb-8594-ce18a92bb9ba.png)

**Comment by supzi-del** [comment]
I would like to work on this under LGMSOC

**Comment by ChitvanRamani22** [comment]
PHAL #325

**Comment by supzi-del** [comment]
So it is not required?

**Comment by ChitvanRamani22** [comment]
@supzi-del as of now, NO.
