### ISSUE TITLE
Landing Page UI🚀 & Footer Css Fix!

### ISSUE THREAD

**Issue by ShubhamSj07** [Tejas1510/Athavani#353]
**Is your feature request related to a problem? Please describe.**
I would like to enhance the home page ui & css of footer section

![athavni-ui-fix](https://user-images.githubusercontent.com/56510414/127735965-54a5d2b6-caa5-40f8-a03d-15efada8e954.JPG)

![athavni-ui-fix-02](https://user-images.githubusercontent.com/56510414/127735973-c249cc97-7788-44b6-8877-b31b6ae27848.JPG)

![athavni-ui-fix-responsive](https://user-images.githubusercontent.com/56510414/127736000-f60afdd7-578b-4ffc-8654-b5887e0d96e7.JPG)

Footer 
![athavni-footer](https://user-images.githubusercontent.com/56510414/127735991-d6a5eb28-e281-483b-aae6-132b770877c4.JPG)

![athavni-footer-responsive](https://user-images.githubusercontent.com/56510414/127736010-28aed241-bd9d-41df-b038-4f254e103e77.JPG)

Pls assign this issue under LGM'21

**Comment by AmeyaJain-25** [comment]
Sure @ShubhamSj07 , Go ahead 🚀
