### ISSUE TITLE
background change 

### ISSUE THREAD

**Issue by Khimit** [Tejas1510/Athavani#36]
@Tejas1510 can we **change existing background** to this as shown in pictures below:

![memo0](https://user-images.githubusercontent.com/46605529/103426856-8a4e2000-4be2-11eb-8aa1-b917c768be2a.PNG)
![memo1](https://user-images.githubusercontent.com/46605529/103426862-90dc9780-4be2-11eb-8875-273990e10cea.PNG)
![memo2](https://user-images.githubusercontent.com/46605529/103426866-976b0f00-4be2-11eb-85a7-9623ce8098d9.PNG)
![memo3](https://user-images.githubusercontent.com/46605529/103426868-9934d280-4be2-11eb-8d16-5acaaa7a2a74.PNG)

@Tejas1510 can I do this change?? can you assign this to me??

**Comment by Tejas1510** [comment]
Go ahead @Khimit

**Comment by Khimit** [comment]
@Tejas1510 please assign this to me and also add respective labels along with DWoC
