### ISSUE TITLE
header styling

### ISSUE THREAD

**Issue by Khimit** [Tejas1510/Athavani#38]
@Tejas1510 can we do **changes in header** like this:
![memo1](https://user-images.githubusercontent.com/46605529/103436593-50613600-4c43-11eb-9d01-c66e674d320e.PNG)
![Capture12](https://user-images.githubusercontent.com/46605529/103436595-5a833480-4c43-11eb-92b6-231f33c7aec1.PNG)

@Tejas1510 **I would like to work on this**..

**Comment by Tejas1510** [comment]
Go ahead @Khimit

**Comment by Khimit** [comment]
I need to change code in *.jss2* class but not able to find where it is in
our project folder.
Can you plz help .
I got stuck at that.

**Comment by Tejas1510** [comment]
I think so you want to add some styling which can be added in style.js file

**Comment by Khimit** [comment]
I am able to style heading letters through style.js but not able to change
background colour in heading .

Please suggest something.

**Comment by Khimit** [comment]
@Tejas1510 please review my PR #46
