### ISSUE TITLE
Add a Dislike Button in the Card

### ISSUE THREAD

**Issue by Tejas1510** [Tejas1510/Athavani#4]
Add a Dislike Button like the like button

**Comment by kenkirito** [comment]
can you assign me this issue

**Comment by Sakshi-25** [comment]
Hey @Tejas1510 I would like to work on this issue, can you assign me this please?
1) One can only like or dislike? or both can be done at the same time?
2) One person can like that as many times as he wants,( like I liked on card, then it got incremented, again I clicked again it incremented) 
Is that okay or need to be fixed?

Please assign me these tasks.  @Tejas1510 @kenkirito

**Comment by Tejas1510** [comment]
@Sakshi-25 actually one person can like or dislike only once but you have to add authentication 
Like every user should have a separate account and he should Login and only his memories to be visible to him
So it is a big issue if you want to work you can go ahead
You will given more marks for that

**Comment by Sakshi-25** [comment]
Sure, will try! Kindly assign me this.

**Comment by kenkirito** [comment]
hii can we both work on this task together

**Comment by Sakshi-25** [comment]
yes sure

**Comment by Tejas1510** [comment]
@kenkirito if both you agree you may both will be awarded points

**Comment by kenkirito** [comment]
@Tejas1510  hi i am getting some issues in frontend

**Comment by koolgax99** [comment]
@kenkirito can I help you on this?

**Comment by sanjay270899** [comment]
I would like to work on this.

**Comment by kenkirito** [comment]
@koolgax99  yes u can help

**Comment by kenkirito** [comment]
https://github.com/Tejas1510/Athavani/pull/10#issue-545743652

**Comment by koolgax99** [comment]
Okay I will check it and help you

**Comment by kenkirito** [comment]
@koolgax99  have u solve the bug because i am free now so I will be trying to solve the issue

**Comment by koolgax99** [comment]
Yes @kenkirito I am committing it by EOD

**Comment by kenkirito** [comment]
ok man @koolgax99  see the backend.

**Comment by kenkirito** [comment]
@Tejas1510  hey @kenkirito  and  @koolgax99  we are working together in this issue

**Comment by koolgax99** [comment]
@kenkirito i fixed the problem. however the dislike will not work in the previous posts because the databse is not updated and we do not have the acces to update it.

The dislike button will be working fine on the new posts that will be created after the pull request is merged.

thankyou @kenkirito for giving this opportunity to help.

**Comment by Tejas1510** [comment]
Great Work Guys 
This is the real meaning of the open-source
Thanks for contributing in Team

**Comment by kenkirito** [comment]
@koolgax99  great work man

**Comment by koolgax99** [comment]
Thankyou @kenkirito  and @Tejas1510 for giving me this opportunit.

**Comment by kenkirito** [comment]
hi @Tejas1510  I haven't received pts for this issue in Dwoc

**Comment by koolgax99** [comment]
Even I will get a point right? @Tejas1510

**Comment by Tejas1510** [comment]
@koolgax99 @kenkirito I have added the appropriate label on the merged so you should get points
