### ISSUE TITLE
Improve the layout of Subscribe Mail form

### ISSUE THREAD

**Issue by Tejas1510** [Tejas1510/Athavani#45]
Improve the layout of Subscribe Mail Form to make it look Good

![image](https://user-images.githubusercontent.com/64543913/103458832-ca6fe880-4d31-11eb-82e4-fec4433a7752.png)

**Comment by Khimit** [comment]
@Tejas1510 I would like to work on this

**Comment by Tejas1510** [comment]
@Khimit go ahead

**Comment by kenkirito** [comment]
can you assign me this issue

**Comment by Tejas1510** [comment]
go ahead @kenkirito

**Comment by kenkirito** [comment]
![Uploading React App and 21 more pages - Personal - Microsoft​ Edge 04-01-2021 03_22_56 PM.png…]()

**Comment by kenkirito** [comment]
![React App and 21 more pages - Personal - Microsoft​ Edge 04-01-2021 03_22_56 PM](https://user-images.githubusercontent.com/68530218/103522780-dcbc6480-4ea0-11eb-937e-31bc8dc49919.png)

**Comment by Tejas1510** [comment]
@kenkirito the design looks good but we are requiring the design of subscribe form to be different from the the already made form
just Make a different design and change its color and you are good to make a PR

**Comment by kenkirito** [comment]
ok

**Comment by kenkirito** [comment]
![React App and 21 more pages - Personal - Microsoft​ Edge 04-01-2021 04_13_46 PM](https://user-images.githubusercontent.com/68530218/103527153-eeedd100-4ea7-11eb-9fe5-0d2645073d9c.png)

**Comment by kenkirito** [comment]
should i make a pr

**Comment by Tejas1510** [comment]
Great work @kenkirito 
Go ahead make a PR

**Comment by kenkirito** [comment]
ok

**Comment by kenkirito** [comment]
hii @Tejas1510  cheack my pr

**Comment by chait04** [comment]
can i redesign it.. please asign me to do so

**Comment by Tejas1510** [comment]
@chait04 currently we are having a good design 
You can put your design here and we will check if we can integrate that
