### ISSUE TITLE
Suggest layout for form

### ISSUE THREAD

**Issue by Tejas1510** [Tejas1510/Athavani#5]
Suggest Layout for the form to make it more attractive

**Comment by kanishkaa24** [comment]
Hey!
I would love to work on this issue.

**Comment by Tejas1510** [comment]
@kanishkaa24 you currently have two assigned issue 
You can first finish them and then I will assign you

**Comment by kanishkaa24** [comment]
Okay
Thank you !

**Comment by Aniket31-coder** [comment]
Hey!
I would like to work on this issue. Should we use Figma to design the form and can you send the template of the form?

**Comment by Tejas1510** [comment]
@Aniket31-coder the current form looks fine but if you have a better template which may go good with the project you can share the template and we can have a discussion over it

**Comment by Tejas1510** [comment]
You can use figma to create the basic layout and if approved you can create the form using material UI components for which you will be getting extra points

**Comment by Aniket31-coder** [comment]
Okay, sure. Thanks for guiding!!

**Comment by Aniket31-coder** [comment]
Hey!
I have created a basic layout, please let me know if any changes are required!!
![image](https://user-images.githubusercontent.com/55101835/103165904-5de17f00-4843-11eb-9831-d1ef4dd8e643.png)

**Comment by Tejas1510** [comment]
That's look Pretty Cool @Aniket31-coder 
Just One Question will it go good with our Background as it is also yellow in Color
If you Can attach a screenshot of the complete homepage then it will be easy to decide
Else the design is Awesome

**Comment by Aniket31-coder** [comment]
Yes, that's the reason I chose yellow, I will send you the complete homepage soon!
Thanks!

**Comment by Tejas1510** [comment]
Sure would be happy to merge your work

**Comment by Aniket31-coder** [comment]
Hi,
I have done making the final layout and the complete homepage looks like this.
![image](https://user-images.githubusercontent.com/55101835/103168682-4615f500-485b-11eb-89ca-18a22b3a4154.png)

But when we start writing the text goes between two colors yellow and white
![image](https://user-images.githubusercontent.com/55101835/103168711-837a8280-485b-11eb-89ad-d2faf2508aa1.png)

Could you please tell if it is fine or suggest any changes which would make the text go in a single color?

**Comment by Tejas1510** [comment]
@Aniket31-coder the design looks good but I would suggest to choose a different colour for the form as it gets mixed with background 
It should clearly evident rest everything is ok
For text input let it be simple black

**Comment by Aniket31-coder** [comment]
Okay, sure!

**Comment by Aniket31-coder** [comment]
Hey!
I have changed the color as per your feedback!
![image](https://user-images.githubusercontent.com/55101835/103169401-431e0300-4861-11eb-949f-541224526f7b.png)
Could you tell if this color looks good?

**Comment by Tejas1510** [comment]
Go ahead and make a Pr @Aniket31-coder 
It looks good to me

**Comment by Aniket31-coder** [comment]
Thanks for helping me and accepting my idea!

**Comment by kanishkaa24** [comment]
As I have one issue assigned, Can I work on this one too?

**Comment by Tejas1510** [comment]
This issue is completed
