### ISSUE TITLE
Concurrently running two servers at once 

### ISSUE THREAD

**Issue by koolgax99** [Tejas1510/Athavani#50]
### **Current Status**
Now to run the application we go to the client and server folder separately and then run both the servers in two different terminals. This takes up a lot of time and also newbies find it difficult to follow this instruction.

### **After adding the feature**
After adding this feature, we can just run the server folder's server which will concurrently run both the frontend and the backend server.

### **Why this feature?**
As we know time is precious, doing this save a lot of time and also its very for any beginner to follow this instruction. There is no need to go to both the folders and run the server.

**Comment by koolgax99** [comment]
@Tejas1510 can you please assign me this issue if you like the feature. I already started working on this.

**Comment by Tejas1510** [comment]
All the member of the group are new to MERN stack so we keeping it quiet simple 
Run frontend and then run the server
Also for the any frontend issue you don't need to run backend as it is hosted on heroku and up and running 
So lets keep it simple for the time being
If we require this at the end I will assign you

**Comment by koolgax99** [comment]
ok @Tejas1510 got your point. Thankyou for explaining it.
