### ISSUE TITLE
Toggle details

### ISSUE THREAD

**Issue by chait04** [Tejas1510/Athavani#51]
<strong>Message should be hidden initially </strong

![Screenshot (176)](https://user-images.githubusercontent.com/59140343/103768439-82f69e80-5048-11eb-9d54-3df91dd1be7b.png)

**Comment by shubhraagarwal** [comment]
I would like to give a try on this issue. Kindly assign it to me.

**Comment by Tejas1510** [comment]
@chait04 you have already 2 issue assigned so I would assign it to @shubhraagarwal

**Comment by Tejas1510** [comment]
Go ahead @shubhraagarwal

**Comment by shubhraagarwal** [comment]
Thank you. How much time do I have to solve this issue?

**Comment by Tejas1510** [comment]
At the earliest

**Comment by shubhraagarwal** [comment]
Okay, will do it by tomorrow noon

**Comment by shubhraagarwal** [comment]
This issues dosent have the DWOC tag.  Can you please add that?
