### ISSUE TITLE
Add Authentication

### ISSUE THREAD

**Issue by Tejas1510** [Tejas1510/Athavani#6]
Add a login and signup page and the data should be stored in a database and every user should be shown his corresponding memory only

**Comment by kenkirito** [comment]
can i work on this issue

**Comment by Tejas1510** [comment]
@kenkirito GO ahead
Just State what is your Plan going ahead

**Comment by shrushti2000** [comment]
I would like to work on this issue. 
1.Whenever the user opens the application he/she will be shown the signin page and if he/she is not registered,we will redirect him to signup page.
2.After successfully signin ,we will redirect user to the main page/homepage wherein he will see memories created by other users and can like the memories created by other users. Also user can create his own memory after signing in.
3. we can provide a feature for the user wherein he can edit his memory and that can be done only by authorized (logged in)users.
4. Also we can add logout option.

Is this approach correct? @Tejas1510 
Or is there anything else that you are planning of?

**Comment by Tejas1510** [comment]
The idea is fantastic
Just keep in mind that user will be able to like all post but can update or delete his or her post only
Else the idea is good
It is a Level-5 idea
Go ahead @shrushti2000 
If properly executed I may even increase the points

**Comment by shrushti2000** [comment]
yes sure.
I will try my best.

**Comment by Tejas1510** [comment]
Go ahead @shrushti2000

**Comment by chait04** [comment]
hey @shrushti2000 if u need any help with this let me know..
or u can assign me this issue

**Comment by Tejas1510** [comment]
Go ahead @chait04

**Comment by sanjay270899** [comment]
I would Like to work on this.

**Comment by Tejas1510** [comment]
Go ahead @sanjay270899

**Comment by Tejas1510** [comment]
@sanjay270899 How is the Progress

**Comment by kenkirito** [comment]
@Tejas1510 can I take this issue

**Comment by sanjay270899** [comment]
> @sanjay270899 How is the Progress

@Tejas1510, I will send 2 PRs for both the issues by tomorrow.
