### ISSUE TITLE
Integrate Welcome and Greeting  Bot 

### ISSUE THREAD

**Issue by akrish4** [Tejas1510/Athavani#60]
**Is your feature request related to a problem? Please describe.**
I can make a welcome and greeting bot which will welcome all users who opens a issue and pull request for the first time
using a config.yml file
Kindly do assign me

If you feel this is a great idea!
Please assign it to me.
**Describe the solution you'd like**

using a config.yml file , I can make it , and I am experienced in it 

**Describe alternatives you've considered**
No alternative needed i am experienced and solution will work 

**Additional context**

For reference, check out: https://github.com/apps/welcome

**Comment by kanishkaa24** [comment]
Can I work on this issue?

**Comment by akrish4** [comment]
> Can I work on this issue?

kindly do check other unassigned issues @kanishkaa24

**Comment by akrish4** [comment]
I have opened a pr for the same @Tejas1510

**Comment by akrish4** [comment]
#67  PR
