### ISSUE TITLE
Mail data rendering in html

### ISSUE THREAD

**Issue by Ashuto7h** [Tejas1510/Athavani#62]
currently the mails we get are simply json objects. render that in HTML.

assign this issue to me.

**Comment by Ashuto7h** [comment]
There are some problems that I am unable to solve.
* The cursive font looks different on mails. maybe it's an issue with mobile fonts.
* The texts are not getting positioned well in the mail as I wanted them.
![Screenshot_20210112_194708](https://user-images.githubusercontent.com/53266261/104326852-327fb500-5510-11eb-826b-48932c1924ac.jpg)

**Comment by Ashuto7h** [comment]
should i make a pull request?

**Comment by Tejas1510** [comment]
Go ahead this looks Good To me
