### ISSUE TITLE
[Fix] Create memory form

### ISSUE THREAD

**Issue by Ashuto7h** [Tejas1510/Athavani#63]
Currently, the create memory form is not completely responsive.
on reducing the window size, at some point, it breaks.

The text fields should remain inside the form div on collapsing the window.

**Screenshots**
![image](https://user-images.githubusercontent.com/53266261/104187161-70f86f80-543d-11eb-8700-0246cf103f7e.png)

The border of Text Fields doesn't match outline border.

**Screenshots**
![image](https://user-images.githubusercontent.com/53266261/104188835-dc434100-543f-11eb-88d0-9d0221a492c8.png)

Also the subscribe heading disappears on scrolling.

**Screenshots**
![image](https://user-images.githubusercontent.com/53266261/104188588-75be2300-543f-11eb-8428-e953a1f72bae.png)

**Desktop**
 - Browser [Firefox]

Screen Size 
600px to 900px

**Comment by Aarush-Goyal** [comment]
I would like to work on it @Ashuto7h

**Comment by nehaparmar99** [comment]
I'd like to work on it.

**Comment by Ashuto7h** [comment]
Why this issue is still not assigned to anyone?

**Comment by Tejas1510** [comment]
@Ashuto7h the screen looks good on my side
![image](https://user-images.githubusercontent.com/64543913/106140104-52f87200-6194-11eb-9572-42d170ae25df.png)

**Comment by Tejas1510** [comment]
It is totally responive
