### ISSUE TITLE
Contributors.md file 

### ISSUE THREAD

**Issue by akrish4** [Tejas1510/Athavani#64]
Hi @Tejas1510 

I would like to add a contributors file which consists of all contributors along with their profile image and name in tabular format 

Let me know if you are interested in this 

Kindly issue me and also pls do a add a great label to motivate myself and make my contribution valuable for me

**Comment by Tejas1510** [comment]
@akrish4 the issue is already solved
You can work on another issue
BTW thanks for creating the issue
