### ISSUE TITLE
[Suggestion] Using nodemon as dev dependency & updating server script to `node index.js`

### ISSUE THREAD

**Issue by Aarush-Goyal** [Tejas1510/Athavani#65]

**Comment by Tejas1510** [comment]
Can you explain a bit more

**Comment by Aarush-Goyal** [comment]
In package.json file. change file like this
```javascript
"scripts":{ 
   "start": "node index.js", 
   "start-dev": "nodemon .index.js"
 },
```
and then execute npm run start-dev for running the development server

**Comment by Aarush-Goyal** [comment]
This article may help :
https://www.freecodecamp.org/news/you-should-never-ever-run-directly-against-node-js-in-production-maybe-7fdfaed51ec6/
