### ISSUE TITLE
Automating webpage

### ISSUE THREAD

**Issue by himanshu007-creator** [Tejas1510/Athavani#70]
I would like to create a script that could be run in CLI and open the website.
Please add DWOC label to it and assigne me this issue.

**Comment by Tejas1510** [comment]
Can you explain its need
We already have our website hosted

**Comment by himanshu007-creator** [comment]
> Can you explain its need
> We already have our website hosted

yes sure, i will create a bash script , running which website will automatically open in web browser.
It will be helpful to those using  linux. It will enable users to open your website without even opening web browser. Run the script and wham!!!
website opens.
If you find it goot to go, assigne me this issue and add "DWOC and level-3 tags

**Comment by Tejas1510** [comment]
Go ahead @himanshu007-creator

**Comment by himanshu007-creator** [comment]
> Go ahead @himanshu007-creator

done sir https://github.com/Tejas1510/Athavani/pull/83
