### ISSUE TITLE
[feature] forget password

### ISSUE THREAD

**Issue by Ashuto7h** [Tejas1510/Athavani#75]
Implement a solution for retrieving the password, in case if somebody forgets his password.

**Comment by sanjay270899** [comment]
@Ashuto7h Sure.

@Tejas1510 Should I build this feature?

**Comment by Tejas1510** [comment]
@Ashuto7h go ahead

**Comment by Tejas1510** [comment]
@sanjay270899 since @Ashuto7h has come with the issue he will be preferred first

**Comment by Tejas1510** [comment]
@Ashuto7h will you be working on the issue or should I assign @sanjay270899

**Comment by Ashuto7h** [comment]
You can assign it to @sanjay270899

**Comment by Tejas1510** [comment]
Go ahead @sanjay270899

**Comment by sanjay270899** [comment]
@Tejas1510 You can close this issue if you wish.
