### ISSUE TITLE
Responsiveness of the landing page.

### ISSUE THREAD

**Issue by nehaparmar99** [Tejas1510/Athavani#76]
**Describe the bug**
The create a memory form and the subscription div aren't responsive.

**Expected behavior**
Should resize as per screen size.

**Screenshots**
![Screenshot_20210123-023725__01](https://user-images.githubusercontent.com/48972593/105547376-70f14d00-5d24-11eb-868b-89fc2d9fc0bc.jpg)
![Screenshot_20210123-023731__01](https://user-images.githubusercontent.com/48972593/105547394-72bb1080-5d24-11eb-8b0a-682c47fdcf6e.jpg)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows
 - Browser [e.g. chrome, safari]Chrome
 - Version [e.g. 22]87

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6]OnePlus7
 - OS: [e.g. iOS8.1] Oxygen OS 10.3.7
 - Browser [e.g. stock browser, safari]Chrome
 - Version [e.g. 22]87
**Additional context**

**Comment by nehaparmar99** [comment]
I'd like to work on it under DWOC

**Comment by sukhpreet-singh1** [comment]
can you please assign me this issue?

**Comment by Tejas1510** [comment]
@sukhpreet-singh1 thanks for the intrest
The issue is solved know
If the project has more issue we would surely contact you

**Comment by sukhpreet-singh1** [comment]
yeah !! sure
