### ISSUE TITLE
Add a Comment Section

### ISSUE THREAD

**Issue by Tejas1510** [Tejas1510/Athavani#77]
Add a section where the user can comment on someone memory

**Comment by sanjay270899** [comment]
I would Like to work on this.

**Comment by Tejas1510** [comment]
@sanjay270899 first complete the user profile part then I will assign it to you

**Comment by kenkirito** [comment]
can i work on this issue

**Comment by Tejas1510** [comment]
This issue can only be done after the USer profile section is implemented

**Comment by Tejas1510** [comment]
Go ahead @kenkirito

**Comment by Tejas1510** [comment]
When a user comments his corresponding image and name should be shown

**Comment by Tejas1510** [comment]
You can refer to Instagram for a better understanding

**Comment by kenkirito** [comment]
@Tejas1510 working on it

**Comment by Tejas1510** [comment]
@kenkirito what is the progress?

**Comment by sanjay270899** [comment]
@Tejas1510 I would Like to work on this.

**Comment by Tejas1510** [comment]
Go ahead @sanjay270899
