### ISSUE TITLE
Wrong title and Logo

### ISSUE THREAD

**Issue by shubhraagarwal** [Tejas1510/Athavani#79]
**Describe the bug**
The Title of the Website still shows React App and the logo is still the default ReactJS logo. I would like to change the title and update the logo. Kindly assign the issue to me.
![image](https://user-images.githubusercontent.com/67220475/105659833-ba41c800-5eef-11eb-8070-6f8c5a2f2443.png)
I would like to work on this issue under DWOC

**Comment by sanjay270899** [comment]
@shubhraagarwal title of the website is correct.
https://github.com/Tejas1510/Athavani/blob/8cd98cf51d380d522a14d49520341b2db2f1336f/client/public/index.html#L28
It was corrected in Issue #52 by you only. Changes are not yet pushed to the netlify. So it is showing `React App`.

**Comment by shubhraagarwal** [comment]
> @shubhraagarwal title of the website is correct.
> https://github.com/Tejas1510/Athavani/blob/8cd98cf51d380d522a14d49520341b2db2f1336f/client/public/index.html#L28
> It was corrected in Issue #52 by you only. Changes are not yet pushed to the netlify. So it is showing `React App`.

Ook
