### ISSUE TITLE
Take user image as input while signup

### ISSUE THREAD

**Issue by Tejas1510** [Tejas1510/Athavani#85]
Currently when user register we are not taking image as input so we cannot display it in the user profile section

**Comment by sanjay270899** [comment]
I would Like to work on this.

**Comment by sanjay270899** [comment]
@Tejas1510 By the way I have keep this in my mind then only I have implemented Profile Section. I have added the default attribute to profile image of user. So for user without profile image, I have shown below default image.
![image](https://user-images.githubusercontent.com/43892590/106486168-5e6ed480-64d7-11eb-8563-8ba27ae2b749.png)

**Comment by Tejas1510** [comment]
Ya that a good idea @sanjay270899 
The entered image should be stored as base64 image

**Comment by Tejas1510** [comment]
See I want that when user sign up take image as a input and display that image as the profile pic in his bio

**Comment by sanjay270899** [comment]
Like in GitHub, we don't add profile pic when signing. There is an option to change profile after creating account.
So keeping this in mind, I have made Profile image as default. Because not everyone like to put their profile picture while creating account.

Though if want to add option while Sign Up, I can implement this.

**Comment by Tejas1510** [comment]
So user can change his photo at run time when he updates his profile

**Comment by sanjay270899** [comment]
@Tejas1510 Yes. There is an option to update or change Profile Image in edit mode.

![image](https://user-images.githubusercontent.com/43892590/106497931-afd19080-64e4-11eb-9194-88fa97e6b06c.png)

**Comment by Tejas1510** [comment]
Ok good
So i will close this issue
