### ISSUE TITLE
Add a Alert Box

### ISSUE THREAD

**Issue by Tejas1510** [Tejas1510/Athavani#9]
Add an alert box when a user tries to delete a Memory and he is not an admin then an alert is shown
![image](https://user-images.githubusercontent.com/64543913/103165093-9b410f00-4839-11eb-945e-706a2c3a6324.png)
If a user tries to delete and password entered is incorrect then an Alert Box Should be Shown with Password Incorrect Content using Matrial ui

**Comment by sakshikhachane** [comment]
Hi @Tejas151,
I would like to work on this issue. I have experience in making this kind of alert boxes. Kindly assign me this issue.

**Comment by Tejas1510** [comment]
Go ahead @sakshikhachane

**Comment by sakshikhachane** [comment]
@Tejas1510 I have few queries -
1. What message should be popped when a user tries to delete a message?
2. How will one know whether the person creating the memory is a user or admin?
3. What is the password of the admin that is used in order to delete memory?

**Comment by Tejas1510** [comment]
@sakshikhachane 
Currently, we don't have an admin option so all memories are visible to all
So if memory is deleted successfully give a message: Memory Delete Successfully
If a password is incorrect give message: Incorrect Password, cannot delete memory

**Comment by sakshikhachane** [comment]
@Tejas1510 Is this okay?

![React App - Google Chrome 03-01-2021 14_14_24](https://user-images.githubusercontent.com/53635792/103474874-0b1d3f80-4dce-11eb-8de8-290839a49727.png)

**Comment by Tejas1510** [comment]
This is good just place it at the top right corner and not the center
