### ISSUE TITLE
License

### ISSUE THREAD

**Issue by Vrushti24** [Tejas1510/Athavani#91]
**Is your feature request related to a problem? Please describe.**
Here there is no license added 

**Describe the solution you'd like**
I can add MIT license .

**Additional context**
Each and every project have license so this should also have

**Comment by Vrushti24** [comment]
I can work on this please assign me

**Comment by Tejas1510** [comment]
Go ahead @Vrushti24

**Comment by Vrushti24** [comment]
PR #92  done please check @Tejas1510

**Comment by sanjay270899** [comment]
Closing this issue.
