### ISSUE TITLE
Feature: Sign Up Email Verification

### ISSUE THREAD

**Issue by sanjay270899** [Tejas1510/Athavani#96]
Currently, user can create account with any email id.

So, I would like to add verification, so that user can create their account only with verified email.

I would Like to work on this.

**Comment by Tejas1510** [comment]
Go ahead @sanjay270899

**Comment by ashuvssut** [comment]
I think DWoC 'feature' PRs get `level4` tags

`level3` tag is for bugfixes

**Comment by ashuvssut** [comment]
DWoC PRs for 'feature'  get `level4` tags

`level3` tag is for bugfixes
